### ISSUE TITLE
oom errors fail silently with pipelines

### ISSUE THREAD

**Issue by clutchski** [gomodule/redigo#131]
When running a redis instance with `maxmemory-policy noeviction`, redis will return errors for write commands that push memory over the limit.

Either I'm using pipelines incorrectly (possible) or redigo is not returning an error in this case. Here's a (pseudo-code) example:

```
for _, k := range whatever {
        err := conn.Send("zadd", key, score, member) // assume this pushes memory over the limit
        if err != nil {
                return err
        }
}
 _, err = conn.Do("") // this error should be non-nil, but is
```

Note, that similar code that uses a transaction with `MULTI/EXEC` does return the OOM error. You should be able to replicate pretty easily by setting your redis instance to an artifically low memory threshold.

Please let me know if I'm not using pipelines correctly. Thanks.

**Comment by EricLagergren** [comment]
`conn.Do` is missing something like this:

			if e, ok := r.(Error); ok {
				return nil, c.fatal(e)
			}

**Comment by stevenh** [comment]
I believe this was fixed by https://github.com/gomodule/redigo/pull/554 please reopen if not
