### ISSUE TITLE
Problem when doing ScanStruct

### ISSUE THREAD

**Issue by jianhu** [gomodule/redigo#27]
just want to know if this lib be able to scan a struct like this:

``` go
type A struct{
    Prop1 string
    Prop2 []int32   
}
```

from the error message I got when doing ScanStruct, it seems slice of type other than byte are not supported; in the case of the struct above, it will raise an error because of the prop2 property which is not []byte type.

Would like to confirm this with you.

And thanks for the great work.. :)

**Comment by chenzhengit** [comment]
if use the mothed "The workaround is to use encoding/json, encoding/gob or some other encoder to convert the []int32 to and from bytes." ,  it's Inefficient to read  for slice oddly, especially when connecting to an external redis host.
Are there any other good solutions?

**Comment by garyburd** [comment]
@chenzhengit The encoding step cannot be eliminated. It's the application responsibility to do the encoding.  Moving the encoding to Redigo will not make the encoding faster than what an application can achieve.

**Comment by chenzhengit** [comment]
@garyburd All right. It's better to  encoding struct if the struct has silce

**Comment by garyburd** [comment]
Scan to a struct with []byte field or write code specific to your struct type.  The code specific to your type is easy to write and will be more efficient than using ScanStruct.
