### ISSUE TITLE
high error rate Redis Cache error:EOF for redigo 

### ISSUE THREAD

**Issue by zhangruiskyline** [gomodule/redigo#328]
I use redigo connection pool to connect to redis cache. And there was some incident in redis cache so its CPU usage was high for about 1hour, but after redis incident fixed, I found lots of Redis Cache error:EOF and sometimes timeout, is that because all connections in connection pool is in bad state? can redigo remove these bad connection?

**Comment by garyburd** [comment]
If read on the underlying connection times out or returns io.EOF then the the pool will automatically discard the connection.   

Use [Pool.TestOnBorrow](https://godoc.org/github.com/gomodule/redigo/redis#Pool.TestOnBorrow) to check the health of the connection before the connection is returned to the application.

**Comment by zhangruiskyline** [comment]
Thanks, so if I set some maxidle connection number, and redigo detect underline connection health as bad connection, after discard it, will it re create a new connection in connection pool automatically?

**Comment by zhangruiskyline** [comment]
Also regarding `TestOnBorrow`, when we use it in redis check, what should we do when it return some error? 
```
if pool.TestOnBorrow() == nil {
pool.Get()
} else {
//what should we do here?
}
```
or we should while loop to get at least one good connection?

```
while pool.TestOnBorrow() != nil {
}
pool.get()
```

**Comment by zhangruiskyline** [comment]
also what is best practice to use `TestonBorrow`?

Application can loop over maxidle to check whether connection is good? something like this? is it good to NOT set idle timeout so idle connection never timeout?

```
maxTest :=0
while(pool.TestonBorrow!=nil){
maxTest++
if maxTest>maxactive {
break
}
}
pool.get()
```

**Comment by zhangruiskyline** [comment]
I saw in redigo's pool connection get method, if we do not set idle timeout, the underline code already checks the health of link via `pool.TestonBorrow`, right? so application is safe to call only `Get` to get health connection?

		```
for i, n := 0, p.idle.Len(); i < n; i++ {
			e := p.idle.Front()
			if e == nil {
				break
			}
			ic := e.Value.(idleConn)
			p.idle.Remove(e)
			test := p.TestOnBorrow
			p.mu.Unlock()
			if test == nil || test(ic.c, ic.t) == nil {
				return ic.c, nil
			}
			ic.c.Close()
			p.mu.Lock()
			p.release()
		}
```

**Comment by garyburd** [comment]
Health checking is independent of the MaxIdle setting.

The pool calls the application supplied TestOnBorrow function to test the health of the connection. The Pool documentation shows an example function.

If the server is configured with a connection timeout, then the application should set IdleTimeout to a value less than the server's timeout.

The application should call Get() to get a connection.  The pool takes care of checking the health of connections, closing time out connections, opening new connections and so on.

**Comment by zhangruiskyline** [comment]
Thanks, I know health check is independent of max idle, but let's see if I have setting of 20 max idle connection but somehow the server close one idle connection so idle connection becomes 19. next time redigo using pool to connection to server, and can only use 19 available connections. will redigo automatically create a new one so max idle connection get back to 20 again?

**Comment by garyburd** [comment]
The pool dials new connections in the Get method when the pool is empty.
