### ISSUE TITLE
New maintainers needed

### ISSUE THREAD

**Issue by garyburd** [gomodule/redigo#331]
I am stepping down as maintainer of of Redigo on May 1st. Use this issue to suggest and discuss new maintainers for the project. I want to have some consensus on the new maintainers before handing the project off.

**Comment by nilslice** [comment]
Hi @garyburd  - I just spoke with @zshipko and we are interested in helping with maintenance. Please let us know how/if you would like to proceed. 

Thank you for all of your work with this project and so many others.

**Comment by stevenh** [comment]
Hi Gary sorry to hear your stepping down from this project it’s been a pleasure to use and work with you.
Given we use it extensively the team at Multiplay, myself included would be interested in helping maintain redigo.

**Comment by garyburd** [comment]
@nilslice, @zshipko and @stevenh:  Thank you for offering to help.  

I want interested parties to come to a consensus on how the project should be maintained by the end of the month.  At the end of the month, I'll update the repo config to add the new collaborators and remove myself.

**Comment by stevenh** [comment]
Thanks @garyburd, @nilslice & @zshipko would you like to have a talk about this on slack, if so what timezones are you guys in and when would be good?

**Comment by nilslice** [comment]
@stevenh - I'm happy to jump in on slack ([Gophers #redis](https://gophers.slack.com/messages/C0D6L40SW)?).. we could also take the less efficient route and keep in in-thread here so it could be more open to the community. I'm in that channel under the same alias as I am here, so feel free to ping me or we can just keep the conversation going here.

I'm in Mountain Time (Boulder, CO) and can be on and off throughout the day async, or for a scheduled block, will probably need to hold until the weekend or Monday.

**Comment by stevenh** [comment]
Sounds like a plan, I've joined we should give @zshipko a chance to catch up before we start talking in detail but I'm about now :)

**Comment by zshipko** [comment]
I definitely prefer something async, but can figure it out if we want to schedule a discussion. Slack seems to be a good middleground, but I also see the appeal of keeping the conversation in this thread.

I’m in Pacific Time, btw.

**Comment by garyburd** [comment]
@nilslice @stevenh @zshipko:  What's the result of your discussions re: maintaining this project?

**Comment by nilslice** [comment]
@garyburd, 

@stevenh, @zshipko & I haven't had a chance to connect. I think the best way to have this conversation would be here on this thread, since our attempts to do so in a synchronous manner on slack have not shown to be fruitful. 

I have quite a bit of experience with issue triage and responding to quick asks for help or minor debugging via @ponzu-cms, but feature-planning and deep internal understanding of this package is something I was hoping to glean from participation in the project. I would be happy to be an initial point of contact for people on the issue tracker and triage out to others where my experience falls short.

@zshipko & I have worked together in the past; his capabilities and experience with Redis far exceed mine, so working in concert on larger efforts is something I feel quite confident about. I have yet to meet @stevenh, but am looking forward to learning more about him and his work and how we can make the most out of this project.

**Comment by nelz9999** [comment]
Have y'all figured this out? I'd rather not let this project "die on the vine", since it's so widely used. 

@garyburd If you need someone to take ownership because you need to drop it sooner rather than later, I can take custodianship until there's someone else willing to take it on.

**Comment by garyburd** [comment]
This is my monthly checkin to see what's going on with the project. Is there any consensus on new maintainers for the project?

**Comment by elithrar** [comment]
I've bubbled this up on golang-nuts too: https://groups.google.com/forum/#!topic/golang-nuts/3rZaVF6G9j0 - to help signal boost.

My advice for anyone reading this far:

1. The best way to demonstrate capability is to help triage issues. Provide useful feedback, get users to file good tickets, reproduce bugs, and fix documentation.
2. Demonstrating that helps build trust -> makes the argument for giving you read-write controls on the repo easier to make!
3. See no. 1

**Comment by qiangli** [comment]
@garyburd thanks for your great work!  Our micro apps in production depends on it and more will be on the way...
I'm willing to help in any way I can.

**Comment by itamarhaber** [comment]
@garyburd nominating myself - I plan to follow the fine advice provided @elithrar to demonstrate ability and establish trust. My Golang fu is still building, but I hope my Redis background will assist in the effort here. That said, not many open issues/prs here so - last but not least, thanks for making this project (a straightforward Redis client is the most fun to work with imo) and kudus for maintaining it so diligently for so long.

**Comment by garyburd** [comment]
I will transfer ownership to a new maintainer on Monday, April 1st.  Please chime in if you have any thoughts on this issue.

**Comment by stevenh** [comment]
Thanks for update, we’ll continue to help support the project which has been and will continue to be a great asset to the community!

**Comment by garyburd** [comment]
Thank you for offers to help. I am looking for someone to take ownership of the project.

**Comment by garyburd** [comment]
I added two people as collaborators and one has accepted.  I am withdrawing from day to day support of the project.

**Comment by elithrar** [comment]
Thank you for your (years of!) open-source contributions here, @garyburd. You know better than most that it can be hard & thankless work maintaining software.

**Comment by stevenh** [comment]
Indeed thank you for this @garyburd I hope we can continue your great work.

If anyone needs to pull me into issues please feel free to @stevenh but do keep in mind that github's email's don't always get through so don't leave it too long to chase if you don't get a response.
