### ISSUE TITLE
Best practice for redigo(poo) ?

### ISSUE THREAD

**Issue by sleagon** [gomodule/redigo#334]
Redigo, which I am not very familiar with, has been widely used in our projects. However, I dont think the code we wrote is reasonable.

Here is the code:
```go
func (db *RedisDB) GetInt(key string) (content int, err error) {
	conn := db.Option.Pool.Get()
	defer conn.Close()
	if err = conn.Err(); err != nil {
		return
	}
	content, err = redis.Int(conn.Do("GET", key))
	return
}

func (db *RedisDB) GetBool(key string) (val bool, err error) {
	conn := db.Option.Pool.Get()
	defer conn.Close()
	if err = conn.Err(); err != nil {
		return
	}

	val, err = redis.Bool(conn.Do("GET", key))
	return
}
```
Here is what I understood, if we call ```conn.Close()``` every single time we getXX from redis, we can not reuse them anymore.

Anyone would like to give me any nice advice?

**Comment by garyburd** [comment]
You can remove the test of conn.Err().

**Comment by sleagon** [comment]
@garyburd  appreciate for your time. The conn should be closed every single time we do some get/set/xx ? I thought we should just get a conn  for one http request and closed it when request handled. Doest it mater?

**Comment by garyburd** [comment]
If a function executes more than one command on the Redis server, then it's usually best to get a connection from the pool, execute the commands and return the connection to the pool when done.

**Comment by sleagon** [comment]
So, i think we should not extend redisDB, instead, we should extend the conn. Get a new conn when new request come in, do whatever we want on conn, and then close the conn at last.

Thank you very much.
