### ISSUE TITLE
redigo dial in SSL via NAT 

### ISSUE THREAD

**Issue by zhangruiskyline** [gomodule/redigo#335]
In current redigo, if we want to dial via SSL , and not configure the server IP, but instead use some automatically way to find address and dial into node(like dial into cluster node via address returned "`Cluster infor`"), it will perform

```
		if tlsConfig.ServerName == "" {
			host, _, err := net.SplitHostPort(address)
			if err != nil {
				netConn.Close()
				return nil, err
			}
			tlsConfig.ServerName = host
		}
```

I do not understand why we want to only use IP, not port information, because it will fail in case redis nodes is behind NAT, they use same IP but different port to forward. dose redigo assume redis SSL is always behind `:6380` port?

anyway to resolve it?

Thanks
Rui

**Comment by garyburd** [comment]
The snippet of code in the issue sets the [server name](https://godoc.org/crypto/tls#Config.ServerName) used to verify the server's certificate.  The code is unrelated to dialing the underlying network connection. 

If this server name is a problem, then you have the following two options:

- Specify a different [server name](https://godoc.org/crypto/tls#Config.ServerName) in the TLS configuration.
- [Skip name verification](https://godoc.org/github.com/gomodule/redigo/redis#DialTLSSkipVerify).

**Comment by garyburd** [comment]
Skipping name verification allows MITM.  

The package provides complete control over name verification.  It's up to the application to pick what's best for the application.
