### ISSUE TITLE
Does Redigo support Redis 4.0 and go 1.10 ؟

### ISSUE THREAD

**Issue by AttSee** [gomodule/redigo#339]
Great job
Does Redigo support Redis 4.0  and go 1.10؟

**Comment by JordanP** [comment]
I am using Redigo with Redis 4.0 with great success. But I am only using 3 different Redis commands.

Still running Go 1.9 though.

**Comment by redmondnoodle** [comment]
Based on current Travis status (linked from the build badge in the readme), the answer is yes.

**Comment by garyburd** [comment]
Yes
