### ISSUE TITLE
Conn.Err() not working properly for Pool connections

### ISSUE THREAD

**Issue by stelioskat** [gomodule/redigo#346]
If Redis server is running and you create a `Pool` and `Get()` a connection, then disable server, connections from the pool still appear as usable.

**Comment by stelioskat** [comment]
Sorry my mistake, this was referring to an older redigo version.

**Comment by xuyang2** [comment]
@stelioskat Are you using the `TestOnBorrow` function of `redis.Pool{}` ?

**Comment by stelioskat** [comment]
@xuyang2 No, I just created a Pool and got connections with `Get()`

**Comment by garyburd** [comment]
Connections return a non-nil error after a read or write error on the underlying network connection. When a server is disabled, the connection returns a non-nil error after the next use of the connection. 

Use [TestOnBorrow](https://godoc.org/github.com/gomodule/redigo/redis#Pool.TestOnBorrow) to check for disabled servers before a connection is returned from the pool.

**Comment by stelioskat** [comment]
@garyburd Thanks for replying for the hint about `TestOnBorrow`.

I guess my problem relates more to `Err()` method of connection. To get more specific, assume we have a connection `c`, then close the Redis server and execute:

```
err := c.Err()
```

If `c` was `Get()` from a `Pool` then `err` is nil. However, if `c` was created as a single connection, `err` is non-nil, which is expected. 
According to `Err()` documentation, I would expect non-nil no matter how the connection was created.

Am I missing something?

**Comment by garyburd** [comment]
The pool connection Err() method [returns the result of calling Err() on the underlying connection](https://github.com/gomodule/redigo/blob/2cd21d9966bf7ff9ae091419744f0b3fb0fecace/redis/pool.go#L437). 

A [connection's error](https://github.com/gomodule/redigo/blob/2cd21d9966bf7ff9ae091419744f0b3fb0fecace/redis/conn.go#L41) is only set on read or write to the underlying network connection.  Disabling a server is not enough to set to set the error.  This is true for both single connections and pooled connections.
