### ISSUE TITLE
 The slower the conn is used, the more times it is used

### ISSUE THREAD

**Issue by abing10631** [gomodule/redigo#348]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
Get idle connection from Front => Get idle connection from Back
func (p *Pool) get() (Conn, error) {
    ...
   for {
		// Get idle connection.
		for i, n := 0, p.idle.Len(); i < n; i++ {
			//e := p.idle.Front()
                        e := p.idle.Back()
    ...
}

**Comment by garyburd** [comment]
What is the problem you are trying to solve?

**Comment by garyburd** [comment]
Closing because OP has not responded.
