### ISSUE TITLE
Do it support redis-cluster?

### ISSUE THREAD

**Issue by sodowe666** [gomodule/redigo#352]
as title

**Comment by nelz9999** [comment]
No, this library doesn't directly support Redis Cluster. However there are several others that are based on, or use `redigo` in their implementation. Here are a couple that I've used in the past:
* https://github.com/mna/redisc
* https://github.com/chasex/redis-go-cluster

**Comment by garyburd** [comment]
@nelz9999 Thank you for answering the question.
