### ISSUE TITLE
conn.WriteUInt64 <- this one was very easy but written halfway.

### ISSUE THREAD

**Issue by unisqu** [gomodule/redigo#353]
Can you update this? It's really easy to update.

**Comment by garyburd** [comment]
What is the problem that you are trying to solve or fix?

Because there is no WriteUInt64 (halfway written or otherwise), I don't understand what you want updated or why.

**Comment by unisqu** [comment]
would like to return WriteUInt64 value instead of Int64

**Comment by unisqu** [comment]
Sorry i think i posted in the wrong github repo. Sorry. it was another repo.
