### ISSUE TITLE
`NOSCRIPT No matching script. Please use EVAL.`

### ISSUE THREAD

**Issue by jney** [gomodule/redigo#354]
while doing a `script.Do(...)` I recieve the following error: `NOSCRIPT No matching script. Please use EVAL.`

But when i look at the code, it's not supposed to happend

```go
func (s *Script) Do(c Conn, keysAndArgs ...interface{}) (interface{}, error) {
	v, err := c.Do("EVALSHA", s.args(s.hash, keysAndArgs)...)
	if e, ok := err.(Error); ok && strings.HasPrefix(string(e), "NOSCRIPT ") {
		v, err = c.Do("EVAL", s.args(s.src, keysAndArgs)...)
	}
	return v, err
}
```

Any idea how to fix it?

**Comment by itamarhaber** [comment]
Hello @jney 

Have you created the script? What are you doing before `script.Do(...)`?

**Comment by jney** [comment]
I didn't create the script. I think `(s *Script) Do(c Conn, keysAndArgs ...interface{}) (interface{}, error)` is supposed to do it for me, or?

**Comment by jney** [comment]
a little more information, it works locally, and it is failing on aws elasticache

**Comment by jney** [comment]
and i actually just use [go-redis-queue](https://github.com/agilebits/go-redis-queue/blob/master/redisqueue/scripts.go#L8-L17)

**Comment by jney** [comment]
I created once through `redis-ci`:

```
$ redis-cli -h redis.staging.local EVAL "$(cat myscript)" 3 1 1 1
```

I guess it use `EVALSHA` now, so it seems to work (at least no error raised for now). 
It is a really short term fix, I still have to figure out where the problem comes from, because it will probably happen in every of my other environment.

**Comment by garyburd** [comment]
The only explanation for the reported behavior is that EVAL returns the error `NOSCRIPT No matching script. Please use EVAL.`  It seems unlikely that the Redis server will return this error from EVAL.

@jney Please post a simple program showing how to reproduce the problem.

**Comment by jney** [comment]
@garyburd as i told in a previous comment, this is the script included in this [package](https://github.com/agilebits/go-redis-queue/blob/master/redisqueue/scripts.go#L8-L17) which doesn't `EVAL` the script properly. but I don't think it is about `go-redis-queue` or `redigo` as it works as it should locally in a docker, the error only happen on aws' elasticache

**Comment by garyburd** [comment]
Print the error with %q format to verify that the error is exactly `NOSCRIPT No matching script. Please use EVAL` as reported.  Perhaps there's a leading space or other byte that causes `strings.HasPrefix(string(e), "NOSCRIPT ")` to return false.

**Comment by jney** [comment]
with `logger.Errorf("lock script failed: %q", err)` : `"lock script failed: \"NOSCRIPT No matching script. Please use EVAL.\""`

**Comment by garyburd** [comment]
Closing per [my earlier comment](https://github.com/gomodule/redigo/issues/354#issuecomment-408700056).

**Comment by jney** [comment]
@garyburd i don't understand your point..
Isn't `*redis Script.Do` supposed to create the script?

**Comment by garyburd** [comment]
Do() does create the script.  If EVALSHA command returns an error starting with the text "NOSCRIPT ", then Do() falls back to calling the EVAL command.  The EVAL command creates the script. 

The only explanation for what you reported is that EVAL returns the error `NOSCRIPT No matching script. Please use EVAL`,  This seems unlikely.  I suspect something else is going on, but it's difficult to know because you have not posted a simple program showing how to reproduce the problem.

**Comment by jney** [comment]
```go
var lockScript = redis.NewScript(1, `
local key = KEYS[1]
local ttl = redis.call("ttl", key)
if ttl > 0 then return ttl end
redis.call("set", key, "", ARGV[1])
return 0`)

func ttl(c redis.Conn, sessionID string) int {
	ttl, err := redis.Int(lockScript.Do(c, keyPrefix+sessionID, lockDuration))
	if err != nil {
		logger.Errorf("lock script failed: %q", err)
		return lockDuration
	}
	return ttl
}
```

**Comment by jney** [comment]
by the way adding the log line:

```go
fmt.Printf("type/cast: %T\t%t\n", err, ok)
```

give me:

`type/cast: redis.Error	false`

**Comment by jney** [comment]
I think that's the point. 
one package is using `"github.com/gomodule/redigo/redis"` and another one `"github.com/garyburd/redigo/redis"`.
I'll make the `Println` asap
