### ISSUE TITLE
What does ErrNil mean?

### ISSUE THREAD

**Issue by ruandao** [gomodule/redigo#355]
https://github.com/gomodule/redigo/blob/2cd21d9966bf7ff9ae091419744f0b3fb0fecace/redis/reply.go#L23-L24

I have test

     reply, err := redisM.Get().Do("hget", "helloX", "mmm")
	if err == redis.ErrNil {
		fmt.Printf("nnnnwww")
		return
	}
	fmt.Printf("reply: %+v, err: %+v", reply, err)

and get:

    reply: <nil>, err: <nil>

but as [redis hget](https://redis.io/commands/hget) say:

      when field not exist, the reply was nil

**Comment by itamarhaber** [comment]
Hello @ruandao 

To get `ErrNil` you'll need to convert the reply, e.g.:

```go
reply, err := redisM.Get().Do("hget", "helloX", "mmm").String()
```

**Comment by ruandao** [comment]
thank you
