### ISSUE TITLE
How do I only update fields of where the input entry is empty?

### ISSUE THREAD

**Issue by unisqu** [gomodule/redigo#359]
With reference to this question again...
https://github.com/gomodule/redigo/issues/357
I have a struct from A to Z (26 fields of them in total)

                        type UDD struct {
                                A string //content = "John"
                                B string //content = "Male"
                                C string //content = "12345678"
                                D string //content = ""
                                E string //content = ""
                                Z string //content = "FIrst time user"
                        }

The hset values are as above.

When i update the fields, i would only like to update fields where the html field value is not empty or similar to the hash value stored. 
my html form has A to Z input text fields too. if "C" field is empty, dont need to add to hmset. 

i would like to update multiple fields without doing round trip or for loops with reference to the answer provided here which is not efficient
https://stackoverflow.com/questions/51568375/how-do-i-pass-multiple-non-empty-values-of-a-struct-to-hmset-in-golang/51569649?noredirect=1#comment90341331_51569649

Any standard workaround solutions to what I need? Efficient update of redis hash set.

**Comment by garyburd** [comment]
> where the html field value is not empty

Skip the empty fields when constructing the arguments for HMSET.  

     args := []interface{}{"KEY"}
     if s.A != "" {
        args = append(args, "A", s.A)
    }
    ... and so on

    r, err := c.Do("HMSET", args...)

> similar to the hash value stored

Fetch the previous value and compare when adding the arguments.

    if s.A != "" && !similar(s.A, prev.A) {
        args = append(args, "A", s.A)
    }

If you are working with an HTML form, it may be simpler to work with Request.Form or similar instead of a struct:

    keys := []string{"A", "B", "C"}
    args := []interface{}{"KEY"}
    for _, key := range keys {
         v := r.Form.Get(key)
         if v != "" {
            args = append(args, key, v)
       }
    }

**Comment by garyburd** [comment]
You can use whatever code you want to construct arguments to a command.   It's OK to ignore similar functions in this package.

I don't have time to help with questions about the reflect package.  Try StackOverflow.
