### ISSUE TITLE
hmget into struct

### ISSUE THREAD

**Issue by unisqu** [gomodule/redigo#360]
I have a struct from A to Z (26 fields of them in total)

                    type UDD struct {
                            A string //content = "John"
                            B string //content = "Male"
                            C string //content = "12345678"
                            D string //content = ""
                            E string //content = ""
                            Z string //content = "FIrst time user"
                    }
The hset values are as above.

for hgetall, it'll return A to Z hash field items.

                        var UD UDD
                        values, err := redis.Values(c.Do("hgetall", value))
                        if err != nil {
                                fmt.Println("HGETALL", err)
                        }
                        if err := redis.ScanStruct(values, &UD); err != nil {
                                fmt.Println(err)
                        }

the above works great which automatically populates UD struct with the values returned.
                   
however, i would like to only get B,C,D

                        values, err := redis.Values(c.Do("hmget", value, "B", "C", "D"))
                        if err != nil {
                                fmt.Println("HMGET", err)
                        }
                        if err := redis.ScanStruct(values, &UD); err != nil {
                                fmt.Println(err)
                        }

obviously the above doesn't work as expected. Any ways I can accomplish what I'm asking for? only add the values of returned hmget to struct UD.

**Comment by garyburd** [comment]
values, err := redis.Values(c.Do("hmget", value, "B", "C", "D"))
                    if err != nil {
                            fmt.Println("HMGET", err)
                    }
                    if _, err := redis.Scan(values, &UD.B, &UD.C, &UD.D); err != nil {
                            fmt.Println(err)
                    }

**Comment by unisqu** [comment]
Sorry for the late reply. Thanks. Appreciate this.
