### ISSUE TITLE
SYNC command support(?)

### ISSUE THREAD

**Issue by sugilog** [gomodule/redigo#364]
Hi!

I  try to cache redis's data in  my golang-app using `SYNC` command.

`gomodule/redigo` is really useful for redis client, but I get error (panic) when receiving message after command `SYNC`.

```
panic: redigo: bad bulk string format (possible server error or unsupported concurrent read by application)
```

It occurs on [`(c *conn) readReply()`](https://github.com/gomodule/redigo/blob/v2.0.0/redis/conn.go#L540).

I use ...

- Redis 4.0.11
- redigo v2.0.0
- go 1.11.0
- macOSX 10.13.6

**Comment by sugilog** [comment]
I should note what i do. sorry.

just like following.

```
        conn.Send("SYNC")
        conn.Flush()

        for {
                reply, err := conn.Receive()
                // ... handle reply
        }
```

**Comment by garyburd** [comment]
Redigo does not support the Redis internal SYNC command.

**Comment by itamarhaber** [comment]
@garyburd for my education, I would imagine adding it will mean implementing special handling due to its blocking nature, PubSub-like, correct?

**Comment by garyburd** [comment]
The the problem is with the format of the data, not that it blocks.

**Comment by itamarhaber** [comment]
Yep, uncompressing the rdb format isn't trivial - forgot that part :)

**Comment by sugilog** [comment]
Thank you @itamarhaber , @garyburd . It was great leaning. I will consider again.
