### ISSUE TITLE
redis/Pool: Get* performance seems to degrade the longer the application runs

### ISSUE THREAD

**Issue by odeke-em** [gomodule/redigo#367]
Hello there redigo maintainers! Thank you very much for all your great work with this repository.
I have been using for a while and it has been a pleasant experience and a very useful package!

So one of my projects has been adding instrumentation with OpenCensus https://opencensus.io to apps in various languages and some time back, I forked this repository and trace+metrics instrumented as per https://github.com/opencensus-integrations/redigo or https://opencensus.io/guides/integrations/redis/go/

Anyways I am using this package in a production app for a soccer league and overtime I've noticed that the traces are showing that pool.Get is taking considerable time e.g.

My configuration:
```go
var redisPool = &redis.Pool{
	MaxActive: 1000, // Arbitrary value
	Dial: func() (redis.Conn, error) {
		return redis.Dial("tcp", otils.EnvOrAlternates("APP_REDIS_SERVER_URL", "localhost:6379"))
	},
	TestOnBorrow: func(c redis.Conn, t time.Time) error {
		if time.Since(t) < (5 * time.Minute) {
			return nil
		}
		_, err := c.Do("PING")
		return err
	},
}
```

## Traces over time: latency ~230ms
<img width="984" alt="screen shot 2018-10-09 at 3 06 53 pm" src="https://user-images.githubusercontent.com/4898263/46707430-9d294400-cbd5-11e8-9e04-b5bf666aaf9f.png">

## Metrics over time: p99th latency 499ms
<img width="1226" alt="screen shot 2018-10-09 at 3 10 40 pm" src="https://user-images.githubusercontent.com/4898263/46707413-8b47a100-cbd5-11e8-8d12-b1e7913a7a33.png">

## Traces at the beginning: latency ~1ms
<img width="1276" alt="screen shot 2018-10-09 at 3 14 35 pm" src="https://user-images.githubusercontent.com/4898263/46707576-293b6b80-cbd6-11e8-896e-43da28e155a7.png">

## Metrics on restart: p99th latency ~600us
<img width="794" alt="screen shot 2018-10-09 at 3 16 50 pm" src="https://user-images.githubusercontent.com/4898263/46707622-64d63580-cbd6-11e8-9314-28c4013925a9.png">

Perhaps we could perform a long running job to profile and figure out what part of Get degrades performance with time?

Also if we'd like this instrumentation backported to this repository, I am delighted to engage in that action and make it happen :) I was going to reach out anyways too.

Thank you again!

**Comment by odeke-em** [comment]
@garyburd thank you for the response!

Unfortunately my Redis server doesn't seem to have a timeout set
```shell
config get timeout
1) "timeout"
2) "0"
```

**Comment by garyburd** [comment]
Given the pool and server configuration, here's what Get does:

```
for {
   remove connection from free list
   if test on borrow succeeds {
        return connection
   }
   close connection
}

return new dialed connection
```

Here are some possible explanations for the degraded performance:

- The time to execute test on borrow or dial degrades.  
- Connections fail test on borrow, thus causing more connections to be dialed

I think the next step is to instrument the application's TestOnBorrow and Dial functions to determine if they degrade over time.

**Comment by garyburd** [comment]
I am closing because there's not enough information to act on this and there's been no response in 10 days.
