### ISSUE TITLE
monitor

### ISSUE THREAD

**Issue by wangdyqxx** [gomodule/redigo#371]
monitor?

**Comment by itamarhaber** [comment]
Hello @wangdyqxx 

I assume you're asking how to call the Redis `MONITOR` command. Here's a simple example:

```go
	conn, _ := redis.Dial("tcp", "0.0.0.0:6379")
	defer conn.Close()

	conn.Do("MONITOR")
	for {
		line, _ := redis.String(conn.Receive())
		fmt.Printf("%s\n", line)
	}
```

**Comment by wangdyqxx** [comment]
thank

**Comment by wangdyqxx** [comment]
> 你好@wangdyqxx
> 
> 我假设您正在询问如何调用Redis `MONITOR`命令。这是一个简单的例子：
> 
> ```go
> 	conn，_  ：= redis。拨号（“ tcp ”，“ 0.0.0.0：6379 ”）
> 	康涅狄格州。对 {
> 		 line，_ ：= redis 执行（“ MONITOR ”）
> 	 。字符串（康涅狄格州接收（）） 
> 		FMT。Printf（“ ％s \ n ”，行）
> 	}
> ```

thank

**Comment by Sn00pyD0g** [comment]
LOL i think was  most interesting question and answer i have ever found on the internet.... the chemistry between you to was amazing. but this is exactly what i needed to 2021 !!! thx gentlemen

**Comment by cameronelliott** [comment]
I think this might prove there is hope for humanity after all. 😄
