### ISSUE TITLE
Redis losing connection in docker container

### ISSUE THREAD

**Issue by lucasalcantara** [gomodule/redigo#374]
I've created a [post](https://stackoverflow.com/questions/53358036/redis-losing-connection-in-docker-container) on Stackoverflow about this issue but as no one is answering me there I am creating here as well.
So If someone can help me with this I'd be really glad.

**Comment by itamarhaber** [comment]
xref: https://github.com/docker-library/redis/issues/172

**Comment by garyburd** [comment]
Comments on the SO question state that the server sent an error to the client and this package returned that error to the application.  This package is working as intended.
