### ISSUE TITLE
Incorrect data received

### ISSUE THREAD

**Issue by SecureStack** [gomodule/redigo#379]
I am inserting data into two different lists (via patterns) like this:

SET list1-timestamp1 val1
SET list2-timestamp2 val1

SET list1-timestamp3 val2
SET list2-timestamp4 val2

SET list1-timestamp5 val3
SET list2-timestamp6 val3

I need to do this because, these two lists have different expire time (TTL). While list1 expires sooner than the list2, within the list1 TTL these lists should have same data. I am seeing randomly incorrect data in these lists. Any ideas, what could be going wrong?

NOTE: this data is inserted from parsing incoming requests by a server application. And all gets are executed periodically.

**Comment by garyburd** [comment]
If you are having a problem with this Redis client, then post code showing the problem.   If you have a question about Redis commands, please seek help in a general Redis forum.

The SET command works on [strings](https://redis.io/topics/data-types#strings), not [lists](https://redis.io/topics/data-types#lists).

**Comment by garyburd** [comment]
No response received in 10 days.
