### ISSUE TITLE
Update a specific value in list

### ISSUE THREAD

**Issue by jinfagang** [gomodule/redigo#383]
Hi, is there anyway to update a specific value in a list, the list is a series of struct, to update one field in one of the element, how do I access them?

**Comment by itamarhaber** [comment]
Hello @jinfagang 

The elements in Redis Lists are supposed to be immutable, and the way a linked list is made makes it undesirable to access any elements in it if they are not at the ends.

If you know the index of the element, you can use [`LSET`](https://redis.io/commands/lset) to update it. Note that you'll have to update the entire element as you can't access "fields" in it and that this operation has linear time complexity.

**Comment by garyburd** [comment]
@itamarhaber Thank you for answering the question.
