### ISSUE TITLE
Is redigo connection support circuit breaker?

### ISSUE THREAD

**Issue by cxt90730** [gomodule/redigo#384]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

**Comment by garyburd** [comment]
What would a circuit breaker on a connection do?

**Comment by cxt90730** [comment]
To be honest, I am not sure if this is a feature that redigo should have. I used to compare another project "go-redis", which says it has the function "Automatic connection pooling with circuit breaker support." (Of course it only has the interface. ). We do need this functionality in the business because Redis servers sometimes have access or network problems.

**Comment by garyburd** [comment]
It sounds like you are asking about circuit break support for the pool, not the connection.  The pool does not have builtin circuit breaker support.  

Because the pool calls an application supplied function to dial connections, the application can implement whatever policy it wants.
