### ISSUE TITLE
I set the IdleTimeout, but it not work

### ISSUE THREAD

**Issue by yanyumiao** [gomodule/redigo#385]
I set the IdleTimeout, but it not work
test.go :
```
package main
import "github.com/gomodule/redigo/redis"
import "time"
import "fmt"
import "net/http"

var Pool * redis.Pool

func init() {
  Pool = &redis.Pool{
    MaxIdle: 5,
    IdleTimeout: 10 * time.Second,
    //Wait: true,
    Dial: func () (redis.Conn, error) {return redis.Dial("tcp", ":6379")},
  }
}

func handler(w http.ResponseWriter, r *http.Request) {
	con := Pool.Get()
	defer con.Close()
	time.Sleep(5 * time.Second)
	fmt.Println("ok")
}

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":10086",nil)
}
```
and then I start my test: 
`go run test.go`
`for ((i=0;i<100;i++)) do curl 127.0.0.1:10086/ & done;`
after a few minutes:
`lsof -i :6379`
 I find there was still 5 connections keep
so, is tha a bug or I use it wrong ?

**Comment by garyburd** [comment]
Idle connections are pruned in the [Get](https://godoc.org/github.com/gomodule/redigo/redis#Pool.Get) method.

Idle connections will be pruned if the application continues to use the pool.  If the pool is no longer needed, then the application should close the pool.

**Comment by garyburd** [comment]
Closing because no response from original poster in 7 days.

**Comment by garyburd** [comment]
The idle connections will be pruned if the application continues to use the pool.   If the application is done with the pool, then the application should close the pool which will in turn close the connections.

Let's reopen the issue there's a real application scenario where current behavior is a problem.

**Comment by yanyumiao** [comment]
So, the IdleTimeout option means what ?

**Comment by yanyumiao** [comment]
Yes, I did it just as same as what you say
**After waiting a few minutes I find that the number of idle connections was not zero**
Try do it by yourself,  You will find it. ^_^

**Comment by yanyumiao** [comment]
Or my test code was not right ?

**Comment by yanyumiao** [comment]
Well, It looks like that we get different result with same test.
I run it with redis 3.2.4 and go 1.10.1 on my mac book

**Comment by yanyumiao** [comment]
Well, I know it.
It looks like that redigo's IdleTimeout option work in a different way compare with go-sql-driver/mysql's SetConnMaxLifetime option

**Comment by yanyumiao** [comment]
It's not a serious problem, thanks

**Comment by garyburd** [comment]
Based on the name of go-sql-driver/mysql's setting, I don't expect the settings to work the same way. Lifetime and idle time are different concepts.
