### ISSUE TITLE
set pool wait will block all operation

### ISSUE THREAD

**Issue by wzhsh90** [gomodule/redigo#387]
1、 I use connect pool and set wait:true 
2、but i find that all method blocked ,no one connection did

**Comment by garyburd** [comment]
It is expected that wait will block when more than `MaxActive` connections are active.  

- `MaxActive` must be set to a value greater than zero.
- The application must return connections to the pool when done by closing the connections.

**Comment by wzhsh90** [comment]
1、here is my test code
for i := 0; i < 100000; i++ {
		go getPoolTest()
	}
func getPoolTest()  {
	rd:=db.RedisDbModel{}
	pool:=rd.GetPool()
	defer pool.Close()
	//todo other logical
}

**Comment by wzhsh90** [comment]
import (
	"github.com/gomodule/redigo/redis"
	"time"
)

type RedisDbModel struct {
}

var pollList *redis.Pool

func init() {

	host := "127.0.0.1:6379"
	db := 3
	pool := 100
	pollList = &redis.Pool{
		MaxIdle:     pool,
		IdleTimeout: 30 * time.Second,
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")
			return err
		},
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", host)
			if err != nil {
				return nil, err
			}
			_, err = c.Do("SELECT", db)
			if err != nil {
				c.Close()
				return nil, err
			}
			return c, nil
		},
	}
}

func (redis *RedisDbModel) GetPool() *redis.Pool {
	return pollList
}


var scriptObj *redis.Script

func init() {
	var scriptc = `
 redis.call('SET',KEYS[1],"1")
`
	scriptObj = redis.NewScript(1, scriptc)
}
func main() {

	for i := 0; i < 12000; i++ {
		go getPoolTest()
	}
	select {}
}

func getPoolTest() {
	rd := cg.RedisDbModel{}
	pool := rd.GetPool()
	conn := pool.Get()
	defer conn.Close()
	_, err :=scriptObj.Do(conn,"test", "1")
	if err != nil {
		println(err.Error())
	}
}
error 1、 wsasend: An existing connection was forcibly closed by the remote host.
error 2、 No connection could be made because the target machine actively refused it.
error 3、 ERR max number of clients reached

how can solve the problem, waiting for your best suggestion

**Comment by garyburd** [comment]
The application is written to dial thousands of connections to the Redis server. The application bumped into a connection limit on the client OS, the server OS or in the Redis server.  Don't dial that many connections.

Either throttle the number of goroutines executing  `getPoolTest` or set the MaxActive and Wait pool options.

**Comment by wzhsh90** [comment]
I test the same operation by java, no any exception throw.
spring:
  redis:
      database: 1
      host: localhost
      port: 6379
      password:
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 100
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

 @GetMapping("test")
    fun test(){
        for (i in 1..12000) {
            thread(start = true) {
                println(TimeUtil.formatToSecond(LocalDateTime.now())+"===="+i)
                redisUserService.test(i.toString())
            }
        }
    }

    override fun test(num: String) {
        stringTemp.opsForValue().set("test", num)
    }

**Comment by wzhsh90** [comment]
if i set the MaxActive and Wait pool options. this will case cpu to 100%

**Comment by garyburd** [comment]
I edited [this program](https://github.com/gomodule/redigo/issues/387#issuecomment-457066275) to add Wait: true, MaxActive: 100.   The goroutines complete in under 1/2 second and there's no CPU use after that.
