### ISSUE TITLE
Support client setname on dial

### ISSUE THREAD

**Issue by B3rs** [gomodule/redigo#388]
Hi, is it possible to support `CLIENT SETNAME` on dial the same way as we support password?
I think it whould be useful expecially for debugging

**Comment by garyburd** [comment]
Good idea.  The following function should be added.

    func DialClientName(name string) DialOption

**Comment by B3rs** [comment]
I can take care of it, thanks

**Comment by garyburd** [comment]
Fixed by aefe8f574a11aec83b39814aa06c8336a4192f5b.
