### ISSUE TITLE
scan returns partial results if there is a nil value in the response

### ISSUE THREAD

**Issue by mmasouras** [gomodule/redigo#398]
After the fix for https://github.com/gomodule/redigo/issues/396 , the runtime error is gone, but now I get back partial data whenever there is a nil interface in the result.
E.g. here I print the value before calling Scan, and then dest after. The "imgy" field is a nil and everything after is not parsed.

[]interface {}{[]interface {}{"_t", []uint8{0x31, 0x35, 0x34, 0x37, 0x37, 0x35, 0x34, 0x34, 0x39, 0x32}, "imgy", interface {}(nil), "ctitle", []uint8{0x6c}, "location", []uint8{0x4f, 0x72, 0x6c, 0x61, 0x6e, 0x64, 0x6f, 0x2c, 0x20, 0x46, 0x4c}, "ph", interface {}(nil), "mpid", []uint8{0x63, 0x66, 0x3a, 0x6d, 0x3a, 0x64, 0x73}, "tags", []uint8{0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x3a, 0x74, 0x3a, 0x64, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x2c, 0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x3a, 0x74, 0x3a, 0x75, 0x73, 0x65, 0x64, 0x2c, 0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x3a, 0x74, 0x3a, 0x68, 0x61, 0x73, 0x76, 0x69, 0x6e, 0x2c, 0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x3a, 0x74, 0x3a, 0x67, 0x6f, 0x6c, 0x64, 0x77, 0x69, 0x6e, 0x67, 0x2c, 0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x3a, 0x74, 0x3a, 0x68, 0x6f, 0x6e, 0x64, 0x61, 0x2c, 0x77, 0x3a, 0x63, 0x6f, 0x75, 0x63, 0x68, 0x72, 0x69, 0x64, 0x65, 0x2c, 0x66, 0x3a, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x75, 0x73, 0x65, 0x64, 0x2c, 0x63, 0x66, 0x3a, 0x64, 0x3a, 0x31, 0x30, 0x39, 0x2c, 0x63, 0x66, 0x3a, 0x6d, 0x3a, 0x64, 0x73, 0x2c, 0x46, 0x4c}, "currency", interface {}(nil), "created", []uint8{0x32, 0x30, 0x31, 0x39, 0x2d, 0x30, 0x31, 0x2d, 0x31, 0x37, 0x20, 0x31, 0x39, 0x3a, 0x34, 0x38, 0x3a, 0x31, 0x32}, "imgx", interface {}(nil), "url", []uint8{0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x77, 0x77, 0x77, 0x2e, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x6f, 0x72, 0x6c, 0x61, 0x6e, 0x64, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x61, 0x73, 0x70, 0x3f, 0x70, 0x61, 0x67, 0x65, 0x3d, 0x78, 0x50, 0x72, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x26, 0x69, 0x64, 0x3d, 0x36, 0x35, 0x38, 0x31, 0x38, 0x32, 0x31, 0x26, 0x70, 0x3d, 0x33, 0x30, 0x26, 0x73, 0x3d, 0x59, 0x65, 0x61, 0x72, 0x26, 0x64, 0x3d, 0x44, 0x26, 0x76, 0x74, 0x3d, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x25, 0x32, 0x30, 0x25, 0x32, 0x46, 0x25, 0x32, 0x30, 0x73, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x26, 0x66, 0x72, 0x3d, 0x78, 0x50, 0x72, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79}, "title", []uint8{0x32, 0x30, 0x30, 0x35, 0x20, 0x48, 0x6f, 0x6e, 0x64, 0x61, 0xc2, 0xae, 0x20, 0x47, 0x6f, 0x6c, 0x64, 0x20, 0x57, 0x69, 0x6e, 0x67, 0x20, 0x54, 0x72, 0x69, 0x6b, 0x65}, "imgurl", interface {}(nil), "feed", []uint8{0x66, 0x3a, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x72, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x75, 0x73, 0x65, 0x64}, "mileage", []uint8{0x34, 0x30, 0x30, 0x30, 0x30}, "price", interface {}(nil), "imgsmallx", interface {}(nil), "imgurlsmall", interface {}(nil), "imgsmally", interface {}(nil), "st", []uint8{0x46, 0x4c}, "geo", []uint8{0x2d, 0x38, 0x31, 0x2e, 0x33, 0x37, 0x39, 0x32, 0x33, 0x36, 0x35, 0x20, 0x32, 0x38, 0x2e, 0x35, 0x33, 0x38, 0x33, 0x33, 0x35, 0x35}, "vin", []uint8{0x31, 0x68, 0x66, 0x73, 0x63, 0x34, 0x37, 0x30, 0x78, 0x35, 0x61, 0x34, 0x31, 0x31, 0x32, 0x33, 0x33}, "year", []uint8{0x32, 0x30, 0x30, 0x35}, "guid", []uint8{0x36, 0x35, 0x38, 0x31, 0x38, 0x32, 0x31}, "did", []uint8{0x63, 0x66, 0x3a, 0x64, 0x3a, 0x31, 0x30, 0x39}}}

2019/02/05 11:38:16 ParseFTSearchResponse scan post hash: redigo.Scan: cannot assign to dest 0: cannot convert from Redis nil to string

2019/02/05 11:38:16 dest is []string{"_t", "1547754492", "imgy", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}

**Comment by mmasouras** [comment]
FYI it's also being addressed on the other side, but I think the client should also be resilient to this situation. https://github.com/RedisLabsModules/RediSearch/issues/598

**Comment by itamarhaber** [comment]
@mmasouras I've been following this on both ends - thanks for all the effort 👍

**Comment by mmasouras** [comment]
redisearch fixed this on the other side, so I am not aware of any other repercussions of this bug.

**Comment by garyburd** [comment]
4632c21b4f9e4bfb9d976ec42c0fdf84cc717f47 adds support for nil values.

**Comment by mmasouras** [comment]
2019/09/26 15:17:37 [[price <nil> imgurlsmall [104 116 116 112 115 58 47 47 115 116 111 114 97 103 101 46 103 111 111 103 108 101 97 112 105 115 46 99 111 109 47 108 119 105 109 103 47 109 104 47 108 47 50 48 49 57 48 54 49 53 47 53 98 99 56 99 100 101 100 51 54 55 52 49 98 102 53 101 50 98 99 101 53 102 97 100 52 49 102 101 54 100 52 46 112 110 103] feed [102 58 116 104 101 109 111 116 111 114 99 97 102 101 110 101 119] _t [49 53 54 48 53 56 57 57 51 51] title [50 48 49 57 32 77 85 76 84 73 83 84 82 65 68 65 32 49 50 54 48 83 32 84 79 85 82 73 78 71 32 45 32 68 117 99 97 116 105] tags [118 109 58 55 55 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 101 117 114 111 112 101 44 118 109 58 49 52 54 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 97 100 118 101 110 116 117 114 101 52 50 51 44 118 109 58 49 54 50 44 118 109 58 49 57 49 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 100 101 97 108 101 114 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 110 101 119 44 116 58 105 109 97 103 101 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 104 97 115 118 105 110 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 116 111 117 114 105 110 103 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 100 117 99 97 116 105 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 109 117 108 116 105 115 116 114 97 100 97 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 109 117 108 116 105 115 116 114 97 100 97 49 50 54 48 44 119 58 99 111 117 99 104 114 105 100 101 58 116 58 109 117 108 116 105 115 116 114 97 100 97 49 50 54 48 115 44 119 58 99 111 117 99 104 114 105 100 101 44 102 58 116 104 101 109 111 116 111 114 99 97 102 101 110 101 119 44 99 102 58 100 58 55 50 57 44 99 102 58 109 58 97 114 105 44 67 65] location [83 117 110 110 121 118 97 108 101 44 32 67 65] geo [45 49 50 50 46 48 51 54 51 52 57 54 32 51 55 46 51 54 56 56 51] created [50 48 49 57 45 48 54 45 49 53 32 48 57 58 49 50 58 49 51] ctitle [50 48 49 57 32 77 85 76 84 73 83 84 82 65 68 65 32 49 50 54 48 83 32 84 79 85 82 73 78 71 32 68 117 99 97 116 105] mpid [99 102 58 109 58 97 114 105] ct [108] year [50 48 49 57] imgurl [104 116 116 112 115 58 47 47 99 100 110 109 101 100 105 97 46 101 110 100 101 97 118 111 114 115 117 105 116 101 46 99 111 109 47 105 109 97 103 101 115 47 84 104 117 109 98 71 101 110 101 114 97 116 111 114 47 84 104 117 109 98 46 97 115 112 120 63 105 109 103 61 104 116 116 112 115 37 51 97 37 50 102 37 50 102 99 100 110 109 101 100 105 97 46 101 110 100 101 97 118 111 114 115 117 105 116 101 46 99 111 109 37 50 102 105 109 97 103 101 115 37 50 102 97 115 115 101 116 115 37 50 102 105 109 103 37 50 102 110 111 45 105 109 97 103 101 45 105 102 46 112 110 103 38 109 119 61 51 53 48 38 109 104 61 50 48 48 38 102 61 49 38 102 122 61 49] vin [122 100 109 97 97 101 107 119 49 107 98 48 48 55 52 56 53] psd [97 114 105] is [10 15 235 64 147 37 18 23 91 218 35 223 151 70 7 5] mileage [48 48 48 48 48 51] ssc [50 50 55 50] st [67 65] did [99 102 58 100 58 55 50 57] ss [56 56 51 50 57] url [104 116 116 112 115 58 47 47 119 119 119 46 116 104 101 109 111 116 111 114 99 97 102 101 46 99 111 109 47 105 110 118 101 110 116 111 114 121 47 50 48 49 57 45 100 117 99 97 116 105 45 109 117 108 116 105 115 116 114 97 100 97 45 49 50 54 48 115 45 116 111 117 114 105 110 103 45 115 117 110 110 121 118 97 108 101 45 99 97 45 57 52 48 56 55 45 50 54 52 51 48 51 54 105] imgurllarge [104 116 116 112 115 58 47 47 115 116 111 114 97 103 101 46 103 111 111 103 108 101 97 112 105 115 46 99 111 109 47 108 119 105 109 103 47 109 104 47 108 47 50 48 49 57 48 54 49 53 47 49 48 53 101 99 56 98 52 102 102 57 52 50 48 54 97 101 52 51 102 100 51 102 100 57 54 49 57 97 97 56 102 46 112 110 103] ssf [57 51 57 57]]]


2019/09/26 15:17:37 redigo.Scan: cannot assign to dest 0: cannot convert from Redis nil to string

**Comment by stevenh** [comment]
The error is saying your trying to put a nil into a string which isn’t valid, you will need to fix your data type

**Comment by mmasouras** [comment]
I get this result back from redisearch so I can't intervene here. 

The actual hash doesn't have that field in it. In these situations, it would be useful if redigo would return an empty string - unless there are side-effects of that that I don't understand.

127.0.0.1:6379> HGETALL p:734802
 1) "imgurlsmall"
 2) "https://storage.googleapis.com/lwimg/mh/l/20190615/5bc8cded36741bf5e2bce5fad41fe6d4.png"
 3) "feed"
 4) "f:themotorcafenew"
 5) "_t"
 6) "1560589933"
 7) "title"
 8) "2019 MULTISTRADA 1260S TOURING - Ducati"
 9) "tags"
10) "vm:77,w:couchride:t:europe,vm:146,w:couchride:t:adventure423,vm:162,vm:191,w:couchride:t:dealer,w:couchride:t:new,t:image,w:couchride:t:hasvin,w:couchride:t:touring,w:couchride:t:ducati,w:couchride:t:multistrada,w:couchride:t:multistrada1260,w:couchride:t:multistrada1260s,w:couchride,f:themotorcafenew,cf:d:729,cf:m:ari,CA"
11) "location"
12) "Sunnyvale, CA"
13) "geo"
14) "-122.0363496 37.36883"
15) "created"
16) "2019-06-15 09:12:13"
17) "ctitle"
18) "2019 MULTISTRADA 1260S TOURING Ducati"
19) "mpid"
20) "cf:m:ari"
21) "ct"
22) "l"
23) "year"
24) "2019"
25) "imgurl"
26) "https://cdnmedia.endeavorsuite.com/images/ThumbGenerator/Thumb.aspx?img=https%3a%2f%2fcdnmedia.endeavorsuite.com%2fimages%2fassets%2fimg%2fno-image-if.png&mw=350&mh=200&f=1&fz=1"
27) "vin"
28) "zdmaaekw1kb007485"
29) "psd"
30) "ari"
31) "is"
32) "\n\x0f\xeb@\x93%\x12\x17[\xda#\xdf\x97F\a\x05"
33) "mileage"
34) "000003"
35) "ssc"
36) "2272"
37) "st"
38) "CA"
39) "did"
40) "cf:d:729"
41) "ss"
42) "88329"
43) "url"
44) "https://www.themotorcafe.com/inventory/2019-ducati-multistrada-1260s-touring-sunnyvale-ca-94087-2643036i"
45) "imgurllarge"
46) "https://storage.googleapis.com/lwimg/mh/l/20190615/105ec8b4ff94206ae43fd3fd9619aa8f.png"
47) "ssf"
48) "9399"

**Comment by stevenh** [comment]
HGETALL should never return nil so I think you may be missing something.

Either way it’s seems unrelated to this issue which was fixed and closed so best to identify a simple test case and raise a new issue if there really is a problem.

**Comment by mmasouras** [comment]
Thank you for helping out Steven, I opened up this separate issue:
https://github.com/gomodule/redigo/issues/437
