### ISSUE TITLE
redigo: unexpected type for Float64, got type float64

### ISSUE THREAD

**Issue by alexdianomi** [gomodule/redigo#399]
Need I say anymore?

Potential bug found while using this package to mock:

"github.com/rafaeljusto/redigomock"

```

cmd := []*redigomock.Cmd{
		ctx.RedisMock().Command("GET", creativeID).Expect(b),
		ctx.RedisMock().Command("GET", "cimp_" + creativeID).Expect(int64(1)),
		ctx.RedisMock().Command("GET", "cusd_" + creativeID).Expect(float64(0.2)),
	}

	if err := app.CMD_Creative(
		ctx,
		[]string{id},
	); err != nil {
		t.Error(err)
		t.Fail()
	}

	for x := 0; x < 3; x++ {
		if ctx.RedisMock().Stats(cmd[x]) != 1 {
			fmt.Println(
				fmt.Sprintf("Command %d was not used!", x),
			)
			t.Fail()
		}
	}
```

**Comment by garyburd** [comment]
Please show how to reproduce the issue using this package alone.

**Comment by alexdianomi** [comment]
https://play.golang.org/p/CnHYAMKdqoR

**Comment by garyburd** [comment]
The float64 type is not one of the Go types used to represent Redis reply types ([doc](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Executing_Commands)).   The error is correct.

**Comment by alexdianomi** [comment]
Redis command reply types are represented using the following Go types:
Redis type              Go type
error                   redis.Error
integer                 int64
simple string           string
bulk string             []byte or nil if value not present.
array                   []interface{} or nil if value not present.

>> I read this on day one of using redigo. Says nothing about float64 for return types

**Comment by alexdianomi** [comment]
How am I supposed to encode the float to pass to this function?

Answer: []byte("0.2")
