### ISSUE TITLE
Closing a subscription connection from a connection pool hangs forever

### ISSUE THREAD

**Issue by euank** [gomodule/redigo#401]
Pooled connections that are currently being received upon for an active connection can't be reliably closed and returned to the pool. In common use of a connection pool, this can result in an exhaustion of said pool.

I've written a short program that, for me, quite reliably reproduces this, included below:

<Details>

```go
package main

import (
	"log"
	"time"

	"github.com/gomodule/redigo/redis"
)

func main() {
	pool := &redis.Pool{
		MaxIdle: 5,
		Dial: func() (redis.Conn, error) {
			return redis.Dial("tcp", "127.0.0.1:6379")
		},
	}
	pconn := pool.Get()

	sub := redis.PubSubConn{
		Conn: pconn,
	}
	if err := sub.Subscribe("test"); err != nil {
		log.Fatalf("subscribe error")
	}

	waitClosed := make(chan struct{})
	go func() {
		time.Sleep(1 * time.Second)
		log.Printf("trying to close connection")
		err := pconn.Close()
		log.Printf("connection closed: %v", err)
		waitClosed <- struct{}{}
	}()

Outer:
	for {
		log.Printf("waiting for a subscription message")
		switch msg := sub.Receive().(type) {
		case redis.Subscription:
			if msg.Kind == "unsubscribe" {
				break Outer
			}
		case error:
			log.Printf("receive error: %v\n", msg)
			break Outer
		default:
			log.Printf("got message: %T: %#v\n", msg, msg)
		}
	}
	log.Printf("end receive loop, waiting for connection close")
	<-waitClosed
}
```

</Details>

My understanding of what's going wrong is the following:

When `.Close()` is called on a pooled connection, it has a special case for subscription connections:

https://github.com/gomodule/redigo/blob/b9037db4b8b9ef501f28279160ab1a73a2de59ec/redis/pool.go#L406-L424

This includes 'ECHO'ing a blob and then trying to read it.

Unfortunately, if a subscription is already being `Receive()`'d on, the other `Receive` will naturally read that echo's reply before `Close()` can begin to receive.

This leaves `Close` waiting on a receive forever, and that active connection is thus never returned to the pool.

To fix this, it seems like one of the following solutions needs to be implemented:

1. The connection needs to have all other 'receives' forcibly terminated before the echo logic somehow.
2. The echo logic should be removed, and `put` should always be called with `forceClose` for a connection that was in the 'subscription' state.

There might be another solution, but those are the two that seem reasonable to me.

The 2nd seems to be a much easier fix, though it has performance implications for any pool that is subscription-connection-heavy.

**Comment by garyburd** [comment]
Signal the receive loop to exit by unsubscribing the connection. Use a channel to synchronize the call to Close.  See also the PubSubConn example.

```
package main

import (
	"log"
	"time"

	"github.com/gomodule/redigo/redis"
)

func main() {
	pool := &redis.Pool{
		MaxIdle: 5,
		Dial: func() (redis.Conn, error) {
			return redis.Dial("tcp", "127.0.0.1:6379")
		},
	}
	pconn := pool.Get()

	sub := redis.PubSubConn{
		Conn: pconn,
	}
	if err := sub.Subscribe("test"); err != nil {
		log.Fatalf("subscribe error")
	}

	done := make(chan struct{})

	go func() {
		close(done)
		for {
			log.Printf("waiting for a subscription message")
			switch msg := sub.Receive().(type) {
			case redis.Subscription:
				if msg.Count == 0 {
					return
				}
			case error:
				log.Printf("receive error: %v\n", msg)
				return
			default:
				log.Printf("got message: %T: %#v\n", msg, msg)
			}
		}
	}()

	time.Sleep(1 * time.Second)
	log.Printf("trying to unsubscribe connection")
	err := sub.Unsubscribe()
	log.Printf("connection unsubscribed: %v", err)
	<-done
	err = pconn.Close()
	log.Printf("connection closed: %v", err)
}

```

**Comment by euank** [comment]
Adding that extra synchronization does fix the race, but I don't see it documented anywhere that this is necessary.

The documentation does explicitly point out that `Receive` can't be used concurrently, but `Pool`'s documentation makes no mention that the connections it returns do a `Receive` in `Close` sometimes.

Regardless that the example does the right thing, this still seems like an easy to miss foot-gun with little to no hints in the documentation on how to avoid it.

**Comment by garyburd** [comment]
The [documentation says](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Concurrency):

> Connections support one concurrent caller to the Receive method and one concurrent caller to the Send and Flush methods. No other concurrency is supported including concurrent calls to the Do method.
>
> For full concurrent access to Redis, use the thread-safe Pool to get, use and release a connection from within a goroutine. Connections returned from a Pool have the concurrency restrictions described in the previous paragraph.

I'll update the documentation to explicitly mention Close.

**Comment by garyburd** [comment]
Fixe by 4b40ddb4586bdd2805bcfba564ed0dfa28ec3886
