### ISSUE TITLE
ERR Protocol error: expected '$', got '*' 

### ISSUE THREAD

**Issue by mosesyu95** [gomodule/redigo#411]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
ERR Protocol error: expected '$', got '*' 
set 时候出现的错误

**Comment by garyburd** [comment]
Run your application with the [race detector](https://golang.org/doc/articles/race_detector.html).  Fix any problems and report back if if you still get this error.

**Comment by stevenh** [comment]
I'm going to close this issue @mosesyu95 as gary mentioned this seems like an app error not a redigo issue. If you're still seeing an issue please feel free to reopen with more information.
