### ISSUE TITLE
about  pool  connections  recovery

### ISSUE THREAD

**Issue by HiGame** [gomodule/redigo#420]
Hello Everybody！Help!!!

The code is as follows：	
```
for i := 0; i < 50; i++ {
        c := pool.Get()
	c.Do("HSET", "user001", "name", "eva")
	c.Close()
}
fmt.Println("PoolStats...", PoolStats, pool.IdleCount())
time.Sleep(5 * time.Second)
fmt.Println("PoolStats...", PoolStats, pool.IdleCount())
```
open 50 connections then close after use
the idlecount should be  50  because connections  are recovery
but why idlecount  is only 1 ?

![image](https://user-images.githubusercontent.com/6800963/56955590-6e27ef00-6b74-11e9-9da2-4d2f7b962e2a.png)

![image](https://user-images.githubusercontent.com/6800963/56956012-7b91a900-6b75-11e9-9b8d-90bc290d74f5.png)

**Comment by HiGame** [comment]
![image](https://user-images.githubusercontent.com/6800963/56955978-5b61ea00-6b75-11e9-8118-ccebb8777b9a.png)

**Comment by stevenh** [comment]
In your example you only ever use one connection, in serial it results in:
```golang
c := pool.Get()
c.Do("HSET", "user001", "name", "eva")
c.Close()

c := pool.Get()
c.Do("HSET", "user001", "name", "eva")
c.Close()

...
```
So as you can see only one connection `c` is ever open at once.

**Comment by HiGame** [comment]
> In your example you only ever use one connection, in serial it results in:
> 
> ```go
> c := pool.Get()
> c.Do("HSET", "user001", "name", "eva")
> c.Close()
> 
> c = pool.Get()
> c.Do("HSET", "user001", "name", "eva")
> c.Close()
> 
> ...
> ```
> 
> So as you can see only one connection ` c` is ever open at once.

thank you  
My understanding：
c.close() is not close the connection，But  put back to pool ，to the effect that  connection should be
idle，When needed it will be active again

In this case：how to idle a  connection ?

**Comment by HiGame** [comment]
Or say   a  connection  under what context or conditions will be idle?

**Comment by stevenh** [comment]
A connection will be idle if it’s been closed, put back in the pool, and it’s idle timeout hasn’t been hit.

This means connections will be reused avoiding the creation of new connections.

**Comment by HiGame** [comment]
> A connection will be idle if it’s been closed, put back in the pool, and it’s idle timeout hasn’t been hit.
> 
> This means connections will be reused avoiding the creation of new connections.

In fact  when i close a connections, it not idle , at once closed 

pool.IdleTimeout = 0 
If the value is zero, then idle connections are not closed

**Comment by HiGame** [comment]
Does nobody have this problem? 
or It's my wrong way of using it.？

**Comment by stevenh** [comment]
Correct with IdleTimeout = 0 then idle connections will not be closed, for example:
pool.IdleTimeout = 0

c := pool.Get()
c.Do("HSET", "user001", "name", "eva")
c.Close()

c2 := pool.Get()
c2.Do("HSET", "user001", "name", "eva")
c2.Close()

fmt.Println(pool.IdleCount())
...
This will print `2` as the maximum number of active connections was 2, which have both been closed so both those connections are now idle.

If you want connections to always be closed then set IdleTimeout = 1.

**Comment by HiGame** [comment]
> Correct with IdleTimeout = 0 then idle connections will not be closed, for example:
> 
> ```go
> pool.IdleTimeout = 0
> 
> c := pool.Get()
> c.Do("HSET", "user001", "name", "eva")
> c.Close()
> 
> c2 := pool.Get()
> c2.Do("HSET", "user001", "name", "eva")
> c2.Close()
> 
> fmt.Println(pool.IdleCount())
> ```
> 
> This will print `2` as the maximum number of active connections was 2, which have both been closed so both those connections are now idle.
> 
> If you want connections to always be closed then set IdleTimeout = 1.

```
	pool = redis.NewPool(func() (redis.Conn, error) {
		db, err := redis.Dial("tcp", REDIS_ADDR)
		if err != nil {
			fmt.Println("Connect to redis error", err)
			return nil, err
		}
		return db, nil
	}, POOL_SIZE)
	pool.IdleTimeout = 100 * time.Second
	pool.MaxActive = 100

	c := pool.Get()
	c.Do("HSET", "user001", "name", "eva")
	c.Close()

	c2 := pool.Get()
	c2.Do("HSET", "user001", "name", "eva")
	c2.Close()

	c3 := pool.Get()
	c3.Do("HSET", "user001", "name", "eva")
	c3.Close()

	fmt.Println("count=", pool.IdleCount())
```

This will print only 1 !!!  only 1  so  sad

**Comment by HiGame** [comment]
it  should be 3   right?

**Comment by HiGame** [comment]
it should be  3   but  the count = 1   
so  What's the problem?

**Comment by stevenh** [comment]
No that's correct as you *maximum* active connections is just *1*
Try:
```golang
pool = redis.NewPool(func() (redis.Conn, error) {
		db, err := redis.Dial("tcp", REDIS_ADDR)
		if err != nil {
			fmt.Println("Connect to redis error", err)
			return nil, err
		}
		return db, nil
	}, POOL_SIZE)
	pool.IdleTimeout = 100 * time.Second
	pool.MaxActive = 100

	c := pool.Get()
	c.Do("HSET", "user001", "name", "eva")
	c.Close()

	c2 := pool.Get()
	c2.Do("HSET", "user001", "name", "eva")
	
	c3 := pool.Get()
	c3.Do("HSET", "user001", "name", "eva")

        // 3 active connections
        c.Close()
        // 2 active, 1 idle connections
	c3.Close()
        // 1 active, 2 idle connections
        c2.Close()
        // 3 idle connections
	fmt.Println("count=", pool.IdleCount())
````

**Comment by HiGame** [comment]
> No that's correct as your **maximum** active connections is just **1**
> Try:
> 
> ```go
> pool = redis.NewPool(func() (redis.Conn, error) {
> 	db, err := redis.Dial("tcp", REDIS_ADDR)
> 	if err != nil {
> 		fmt.Println("Connect to redis error", err)
> 		return nil, err
> 	}
> 	return db, nil
> }, POOL_SIZE)
> pool.IdleTimeout = 100 * time.Second
> pool.MaxActive = 100
> 
> c := pool.Get()
> c.Do("HSET", "user001", "name", "eva")
> c.Close()
> 
> c2 := pool.Get()
> c2.Do("HSET", "user001", "name", "eva")
> 
> c3 := pool.Get()
> c3.Do("HSET", "user001", "name", "eva")
> 
> // 3 active connections
> c.Close()
> // 2 active, 1 idle connections
> c3.Close()
> // 1 active, 2 idle connections
> c2.Close()
> // 3 idle connections
> fmt.Println("count=", pool.IdleCount())
> ```

i  got  it !   thank vary mu ch

You're a good man !!!
