### ISSUE TITLE
redis pool max active connection

### ISSUE THREAD

**Issue by bluesky1024** [gomodule/redigo#421]
Is there any limit about the setting of max active connection? I tried to establish 1000 connections concurrently for some operations. However, only about 250 coroutines got valid connection, the others return err as follows
```bash
dial tcp 127.0.0.1:6379: socket: too many open files
```
And I checked the configure of redis-server. Its max connections allowed is 10000.
the simple demo is as follow.
```go
package main

import (
	"fmt"
	"github.com/gomodule/redigo/redis"
	"sync"
	"time"
)

func main() {
	pool := &redis.Pool{
		MaxActive:   0,
		MaxIdle:     100,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", "127.0.0.1:6379")
			if err != nil {
				return nil, err
			}
			//if _, err := c.Do("AUTH", password); err != nil {
			//	c.Close()		timeExpireOthers,err := redis.Int64(conn.Do("GET",lockId))
			//	return nil, err
			//}
			//if _, err := c.Do("SELECT", db); err != nil {
			//	c.Close()
			//	return nil, err
			//}
			return c, nil
		},
	}

	wg := sync.WaitGroup{}
	for i := 0; i < 1000; i++ {
		wg.Add(1)
		//time.Sleep(time.Millisecond * 10)
		go func(ind int) {
			defer wg.Done()
			conn := pool.Get()
			defer conn.Close()
			timeExpire, err := redis.Int64(conn.Do("GET", "test"))
			if err != nil {
				fmt.Println(ind, "redis err", timeExpire, err.Error())
				return
			}
		}(i)
	}
	wg.Wait()
	fmt.Println("end")
}
```
Is there any errors in my codes? Thanks for your attention.

**Comment by stevenh** [comment]
That’s an OS limit which can be both system wide, per user and per process.

For Linux you can find some information here:
https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by bluesky1024** [comment]
thanks for your reply. I checked the os limit per user, the result is 256. So that's the gate of my process. Thanks again

**Comment by bluesky1024** [comment]
@stevenh 
I tried to change os limit per user by "ulimit -n 2000". The maxfiles is 12288 and the maxfilesperproc is 10340. And this change works to some extend.
I set the number of concurrent coroutines to get conn  as 500, there is no problem in most time while some pool.Get() still return errorConn{}. When the number is set as 1000, the errorConn{} turns more as follows.
```bash
bash-3.2# go run main.go | grep errorConn | wc -l
      60
bash-3.2# go run main.go | grep errorConn | wc -l
      53
bash-3.2# go run main.go | grep errorConn | wc -l
       0
bash-3.2# go run main.go | grep errorConn | wc -l
      35
bash-3.2# go run main.go | grep errorConn | wc -l
      13
bash-3.2# go run main.go | grep errorConn | wc -l
       0
bash-3.2# go run main.go | grep errorConn | wc -l
       0
bash-3.2# go run main.go | grep errorConn | wc -l
       0
```
the errorConn number seems not so stable.
i use the follow method to avoid errorConn{}
```go
			conn := pool.Get()
			if reflect.TypeOf(conn).Name() == "redis.errorConn" {
				time.Sleep(100 * time.Millisecond)
				conn = pool.Get()
			}
```
Is there some better method to solve the problem?

**Comment by stevenh** [comment]
What’s the actual error?

I suspect you are overloading your redis instance. Don’t forget redis is single threaded, so while it **can** deal with large total number of connections if they all come in really quickly your likely to see issues.

Increasing the socket backlog for the redis server may help but you should really look to adjust the way your using connections to uses a smaller number if possible.

**Comment by bluesky1024** [comment]
## what i want to do
I want to realize a simple distribute lock based on redis and here is my program.
https://github.com/bluesky1024/goMblog/tree/20190425_mblog_to_feed/tools/distributeLock
I run the "TestMultiRedisLock" demo to check whether the program designed right, while the number of coroutine up to 1000, something wrong appears.
## my test
### two same process run as the program writed in one level
* when i run one process, the redis-server's info clients show "connected_clients:480". When i run two processes at the same time, the redis-server's info show "connected_clients:860". 
* It seems proving that my redis instance is not overloading.

### get conn without multi coroutines
In fact, I tried to establish 1000 connections without multi coroutines as follow(To test multi connections, I don't release connections)
```go
	pool := &redis.Pool{
		MaxActive:   4000,
		MaxIdle:     100,
		IdleTimeout: 240 * time.Second,
		Dial: func() (redis.Conn, error) {
			c, err := redis.Dial("tcp", "127.0.0.1:6379")
			if err != nil {
				return nil, err
			}
			return c, nil
		},
	}
	defer pool.Close()

	conn := make([]redis.Conn, 1000)
	for i := 0; i < 1000; i++ {
		conn[i] = pool.Get()
		fmt.Println(reflect.TypeOf(conn[i]).Name())
		res, err := redis.Int64(conn[i].Do("GET", "test"))
		if err != nil {
			fmt.Println("error conn")
		}
		fmt.Println(res, pool.Stats())
	}
```
And all the connections are normal. 
So is there any posibility that redis pool getting connection with multi coroutines at the same time executes wrong somewhere?

**Comment by stevenh** [comment]
There's a library which supports redis distributed locks here:
https://github.com/go-redsync/redsync

The issue with getting multiple connections within goroutines is almost certainly the speed.

As I mentioned you're likely overloading the server with incoming connections.

A few other tips:

1. go files names are typically snake case e.g. redis_lock.go.
2. go package names follow the directory name they reside in so `package redis` vs `package redislock`
3. Avoid globals in the package such as `RedisLockSrv`

**Comment by bluesky1024** [comment]
Thanks for your advices sincerely. I'm new to language go, the code style advices could be much helpful...

I tried to connect another matchine's redis-server in the same way, everything goes well. So there must be somewhere wrong about my configures. And I will check them again.

As for your tip three, if i want to avoid create redis pool repeatly in a process, is there some better method to realize without globals? Or the expense of recreate redis pool can be ignored?

**Comment by stevenh** [comment]
Put a reference to the pool in the lock so to solve number three.

**Comment by bluesky1024** [comment]
what you means is like this?
```go
type redisLock struct {
	LockId   string
	TimeExpire int64
	TimeHoldLock time.Duration
	RedisPool *redis.Pool
}
```
and store the real redisPool parameters in main package?

**Comment by propertyscott** [comment]
The code calls time.Sleep while holding pooled connections.  A simple improvement is to return the connection to the pool before sleeping and reacquire the next time needed.

Applications should strive to use small number connections. Focus on designing for smaller number of connections instead of how to make large number of connections work.

**Comment by bluesky1024** [comment]
@propertyscott Your tip is meanful. And I have done as what you said yesterday. But error conn still appeared. As the demo below shows
```go
package main

import (
	"fmt"
	"net"
	"sync"
)

func main() {
	fmt.Println("start")

	wg := sync.WaitGroup{}
	conns := make([]net.Conn, 1000)
	for i := 0; i < 1000; i++ {
		wg.Add(1)
		go func(ind int) {
			defer wg.Done()
			conns[ind], _ = net.Dial("tcp", "127.0.0.1:6379")
			if conns[ind] == nil {
				fmt.Println("dial fail")
			}
		}(i)
	}

	wg.Wait()
	fmt.Println("end")
}
```
The problem now is that some net.Dial fail when every connection is active in high concurrence condition. the system configures limit the performance of my program.

By the way, it is important to improve my code by releasing connection as soon as possible. Thanks for your advice.

**Comment by stevenh** [comment]
I wouldn’t do that as your creating a new pool on top of the existing seemingly for no reason

**Comment by bluesky1024** [comment]
I don't figure out what you mean... The function "InitRedisLockSrv()" will only be executed at the start of server, and there will be only one pool in the whole process runtime.
