### ISSUE TITLE
ScanStruct and nested struct

### ISSUE THREAD

**Issue by hjzhang98** [gomodule/redigo#424]
If there is a structure inside the structure, the fields after the nested structure are not scanned correctly. The fix is to check the field kind(), skip nested structure conversion, and return nil.

**Comment by stevenh** [comment]
So you have an example of this issue?

**Comment by hjzhang98** [comment]
This issue happens at line 466 in ./redigo/redis/scan.go.  The convertAssignValue(d.FieldByIndex(fs.index), s) returns an err (failed to convert simple string to a structure) on nested structure. ScanStruct() returns on this err and skips all the remaining fields. 

Since we know ScanStruct() does not support nested structure, the field of reflect.Struct should be skipped.

Another solution is to put nested structures at the end of a structure.

**Comment by stevenh** [comment]
Thanks for that but a working example would still be really useful.

**Comment by propertyscott** [comment]
Use the `redis:"-"`  tag to ignore a field:

     type MyType struct {
        Foo string
        Bar  AStructType `redis:"-"` 
    }

**Comment by hjzhang98** [comment]
Tried a few things. The following changes work very well.

Change line 466
	if err := convertAssignValue(d.FieldByIndex(fs.index), s); err != nil {
to
        f := d.FieldByIndex(fs.index)
        if f.Kind() == reflect.Struct {
                continue
        }
        if err := convertAssignValue(f, s); err != nil {

**Comment by propertyscott** [comment]
@hjzhang98 Your suggestion breaks the case where the struct value supports the `scanner.RedisScan` interface.

Another issue with this approach is that it cuts off future enhancements to the package.  If code is added to ignore nested structs, then applications might break if a future enhancement adds support for nested structs.

There is already a feature for ignoring fields.  Is there are reason that you don't want to use it?

**Comment by hjzhang98** [comment]
The structures are defined by others.
