### ISSUE TITLE
Is it or would it be possible to get async responses for commands?

### ISSUE THREAD

**Issue by pablote** [gomodule/redigo#429]
I'm particularly thinking about the zrange and zrangebyscore commands, that return some potentially very large responses. I would ideally like to start processing response as they come, without having to wait until I get the entire range in memory.

**Comment by stevenh** [comment]
No sure how useful that would be as even for large sets you should get them very quickly.

**Comment by stevenh** [comment]
Closing, if you have any more questions on the subject please feel free to re-open.
