### ISSUE TITLE
Goroutine stop working when calling: conn.Do()

### ISSUE THREAD

**Issue by bcashier** [gomodule/redigo#438]
I am using redisgo lib in order to interact with my Redis database.

I want to make Redis store informations in a goroutine so that my program continue working while saving ... and message to be stored are sent using channels to the function responsible to do this tasks.

My goroutine function (The worker):

    func WorkerOne(resultUser <-chan *Both) string {
    
    	conn := redis.Pool.Get()
    	defer conn.Close()

    	var latest int
    	for x := range resultUser {
    		
            conn.Do("MULTI")

    		doneUser := x.doneUser
    
    		if len(doneUser) > 0 {
    			for _, datas := range doneUser {
    				userKey := fmt.Sprintf("user:id:%d", datas.user_id)
    				conn.Send("HINCRBYFLOAT", userKey, "score", datas.score)
    				latest = datas.user_id
    			}
    		}
    		
    
    		conn.Send("SET", "latestUser", latest)
    		conn.Do("EXEC")

            // REST OF THE CODE HERE
    
    	}
    
    }

And here the main code from where i send messages:

    func main() {
    	//...
    	var WorkerOneCH = make(chan *Both)
    	
    	go WorkerOne(WorkerOneCH)
    
    	both := new(Both)
    	both.doneUser = doneUser
    	both.disUser = disUser
    
    	WorkerOneCH <- both
    	//...
    }

### My Problems (I have 2)

1- I don't receive all the messages sent from the main script (Sometimes I get all the messages and sometimes not)

2- "The rest of the code" from WorkerOne function do not start because of `conn.Do("EXEC")` line, but when I add it as goroutine it works: `go conn.Do("EXEC")` and the rest of the code is executed normally.

DO you have any idea of my problem here please ?

**Comment by stevenh** [comment]
A few things:
1. You're not checking your errors from conn methods.
2. You don't need the `if len(doneUser) > 0 {` if there are no elements the `for` wont do anything.
3. I guess `WorkerOne` should be long running, if so I'd recommend getting the connection inside `for x := range resultUser {` so if a connection goes bad you get a new one.
4. The idomatic style for `var WorkerOneCH = make(chan *Both)` is `ch := make(chan *Both)`, I've renamed as even if you have multiple works they can all read off the same channel.
5. Next your channel isn't buffered so you main will stall until `WorkerOne` processes the entry anyway.

Can't tell much else without the structures.

**Comment by bcashier** [comment]
@stevenh Thank you sir for your answer.

It seem that I had to wait for goroutine to finish the job to solve this problem.
