### ISSUE TITLE
Unable to convert result to redis.Strings

### ISSUE THREAD

**Issue by shaneHowearth** [gomodule/redigo#443]
I have been battling to convert a slice of strings held in redis to []string in go.
```go
dataset, err := redis.Values(conn.Do("HGETALL", id))
a.Tags, err = redis.Strings(dataset[3].([]byte), nil)
```

gives error
unexpected type for Strings, got type []uint8, []uint8

But if I println the data:
log.Println("Dataset: ", string(dataset[3].([]byte))) 

Dataset:  [red blue]

I've realised that the error is coming from the following function (it's looking for a  []interface{}, but I'm only passing in an interface{} that happens to be []byte)
https://github.com/gomodule/redigo/blob/bb5990dc771ab24e169aaea90ee3b9ad50cffce9/redis/reply.go#L246

I've not found a way, as yet, to get the []string back out of redis with redigo.

**Comment by stevenh** [comment]
You want something more like:
```go
a.Tags, err := redis.Strings(conn.Do("HGETALL", id))
```

If you want a specific field for tags, `HGET` or `HMGET` might be better. Alternatively `ScanStruct` might be better for your use case.

**Comment by shaneHowearth** [comment]
ScanStruct produced an empty struct (that is none of the fields were populated :(

Your suggestion would give me all the fields of that id, it's only one field that is problematic
think 1: string, 2: string, 3:[]string and it's the third field that I cannot pull out of redis

**Comment by stevenh** [comment]
Did you setup the struct with the correct field names so `ScanStruct` worked?

Hashes only store simple strings, so if you're expecting a `[]string` that wont work.

**Comment by shaneHowearth** [comment]
Yes, I setup the struct correctly.

The silly thing about your other comment is if I cast dataset[3] to a string , as I mentioned in my original report, I get [string1 string1] indicating that it's a []string. The *problem* is getting redigo to convert those bytes into a []string (I cannot split on whitespace as I may have strings with whitespace in them (I think I will check if there is some sort of terminator in the []byte though

**Comment by stevenh** [comment]
> Yes, I setup the struct correctly.
An example would help validate this.

> The silly thing about your other comment is if I cast dataset[3] to a string , as I mentioned in my original report, I get [string1 string1] indicating that it's a []string. The _problem_ is getting redigo to convert those bytes into a []string (I cannot split on whitespace as I may have strings with whitespace in them (I think I will check if there is some sort of terminator in the []byte though.

If you look in redis directly what do you see? I suspect you'll see just a pure string as that's all a hash supports:
https://redis.io/commands/hset
https://redis.io/commands/hget

**Comment by shaneHowearth** [comment]
Actually, I think you're right. I've decided to take another route, that is, create a list of strings alongside the hash, and get it that way
