### ISSUE TITLE
RedisArg: use it in conjunction with `AddFlat`

### ISSUE THREAD

**Issue by cyx** [gomodule/redigo#444]
## Context

Given this scenario:

```
type User struct {
    CreatedAt Time `redis:"created_at"`
}

type Time struct {
    time.Time
}

func (t Time) RedisArg() interface{} {
  return t.Unix()
}
```

We'd expect that doing `redis.Args{}.AddFlat(&User{Time: Time{time.Now()}})` would utilize the underlying `RedisArg` -- but currently it does the default marshaling strategy for `interface{}` instead.

It does seem like the diff is relatively small in doing this, e.g.:

```diff
-                       args = append(args, fs.name, fv.Interface())
+                       if arg, ok := fv.Interface().(Argument); ok {
+                               args = append(args, fs.name, arg.RedisArg())
+                       } else {
+                               args = append(args, fs.name, fv.Interface())
+                       }
```

Does this seem like a good change?

**Comment by stevenh** [comment]
This looks sensible to me, a PR which does this including test would be most appreciated :)

**Comment by cyx** [comment]
@stevenh please see the PR over at #446
