### ISSUE TITLE
Without redisgo.UInt64s()?

### ISSUE THREAD

**Issue by WickyLeo** [gomodule/redigo#447]
i can use
redisgo.Int64s()
redisgo.Uint64()
But:
without redisgo.UInt64s()

**Comment by stevenh** [comment]
Feel free to put in a PR to add it 😊

**Comment by xuanskyer** [comment]
#453 @stevenh  I added a pull request about this issue

**Comment by stevenh** [comment]
Thanks for the PR, this is still pending fixes. If you could fix then we can get it merged.

**Comment by xuanskyer** [comment]
@WickyLeo Uint64s() has been merged

thinks for @stevenh 's help!
