### ISSUE TITLE
Lua support without embedded scripts

### ISSUE THREAD

**Issue by swayamraina** [gomodule/redigo#448]
I see the only way to run **lua** scripts currently is to create an embedded **lua script** and then use the `Script` object to run the function.

Can we introduce a new function which accepts a file path and runs the lua script in redis?

**Comment by swayamraina** [comment]
I would love to raise a PR for the enhancement (if the enhancement is accepted for dev work)

**Comment by stephenandwood** [comment]
You can run a Lua script from a file like this:

     p, err := ioutil.ReadFile(path)
     if err != nil {
           // handle error
    }
    result, err := c.Do("EVAL", p, 0, arg1, arg2)
    if err != nil {
         // handle error
    }

There are ways to improve the code.  The application can hash the file contents and use EVALSHA for later invocations of the script.  The application can check the modtime on the file and reload on change.

There's a proposal to [add static asset bundling to the Go tool](http://golang.org/issue/35950).  The builtin bundling will be the preferred way to distribute an external Lua script with a Go binary.  Should the design of an API here wait on the Go tool feature?

**Comment by stevenh** [comment]
There are already ways to do this we use https://github.com/jteeuwen/go-bindata, note it's archived so may be better to use something that's supported.

Reading a file from disk would add significant delay in a hot path so its not really a good idea.

If you want to use on disk files you could always load them on application start.

**Comment by swayamraina** [comment]
@stephenandwood this feature is not too critical and can wait for the go team to pull out the exact solution. Let's keep this issue open until the go release or until someone needs the feature before that.

**Comment by stevenh** [comment]
I think its ok to close this as this can be achieve now with more work?

**Comment by swayamraina** [comment]
@stevenh This feature was required for us so had created a wrapper module for this.
refer: https://github.com/swayamraina/lua-scanner
The solve involves around injecting `lua` scripts to application in-memory cache at startup.

Not sure when the community release will come for go or if we have had a progress on that front.

**Comment by stevenh** [comment]
Going to close this as there are options outside of this repo which solve this problem.
