### ISSUE TITLE
SUNION key1 key2....  got null slice  by redis.strings

### ISSUE THREAD

**Issue by civet148** [gomodule/redigo#449]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

In my redis , has few keys .  redis.strings(conn.Do("SUNION", "Key1"))  works well if just one key , but, when I have two or more key to get values,  I just got  null slice of string.

**Comment by stephenandwood** [comment]
Show the exact code that you used when trying multiple keys.

**Comment by civet148** [comment]
thanks for your answer, I have got the right way .
