### ISSUE TITLE
get an non-exist key , return an err

### ISSUE THREAD

**Issue by ou-bing** [gomodule/redigo#450]
when i  get an non-exist key，err is nil :

```
value, err := con.Do("GET", "non-exist-key")
fmt.Println(value)
fmt.Println(err)

$<nil>
$<nil>
```
But when i used `redis.String`，the `err != nil` is true

```
value, err := redis.String(con.Do("GET", "non-exist-key"))
fmt.Println(value)
fmt.Println(err)

$
$redigo: nil returned
```

**Comment by stephenandwood** [comment]
The results described in this issue match the [documentation](https://pkg.go.dev/github.com/gomodule/redigo/redis?tab=doc#String).

If you are OK using the empty string when the key is missing, then ignore [ErrNil](https://godoc.org/github.com/gomodule/redigo/redis#ErrNil).

```
value, err := redis.String(con.Do("GET", "non-exist-key"))
if err == redis.ErrNil { err = nil }
fmt.Println(value)
fmt.Println(err)

```

**Comment by stevenh** [comment]
This is correct behaviour, nil for the value in the first case indicates no value hence the key doesn't exist.

Using redis.String makes this more obvious by actually checking for nil when a string was expected and returning redis.ErrNil.
