### ISSUE TITLE
Error - redigo.Scan: Cannot convert from Redis bulk string to *string 

### ISSUE THREAD

**Issue by novikov1337danil** [gomodule/redigo#451]
I have a struct like that
```
type User struct {
	Nickname  *string `json:"nickname"`
	Phone     *string `json:"phone"`
}
```
Values ​​are placed in redis with `HMSET` command. (values ​​can be `nil`)

Now I'm trying to scan values ​​into a structure:

```
values, err := redis.Values(Cache.Do("HMGET", "key", "nickname", "phone" )

var usr User

_, err := redis.Scan(values, &usr.Nickname, &usr.Phone)
```
But I get an error

> redigo.Scan: cannot assign to dest 0: cannot convert from Redis bulk string to *string 

Please tell me what I'm doing wrong?

**Comment by stevenh** [comment]
As the message says you're trying to store a string into a string pointer drop the &'s from your Scan call.

**Comment by novikov1337danil** [comment]
@stevenh 

Thanks for trying to help. Now i get 

> runtime error: invalid memory address or nil pointer dereference

**Comment by stevenh** [comment]
What’s your code now if you did the & removal you will need to init your struct ScanStruct would do all that for you

**Comment by stephenandwood** [comment]
See [discussion on SO](https://stackoverflow.com/questions/59405352/error-redigo-scan-cannot-convert-from-redis-bulk-string-to-string).
