### ISSUE TITLE
Get conn`s ip and port

### ISSUE THREAD

**Issue by itczl22** [gomodule/redigo#452]
In our use cases, we always need to get conn`s local and remote ip and port to do someting like request report. Could we add two function like GetLocalAddr()(ip string, port int) and GetRemoteAddr()(ip string, port int) ?

**Comment by stevenh** [comment]
Not sure I follow you, as connections are pooled, I can't picture what you're trying to do.

**Comment by itczl22** [comment]
> trying

In actual use, we have many conn instances and maintain a conn-dimensional pool by ourselves. When taking a conn from this pool, we want to obtain it`s remote ip and port .

**Comment by itczl22** [comment]
> Not sure I follow you, as connections are pooled, I can't picture what you're trying to do.

In actual use, we have many conn instances and maintain a conn-dimensional pool by ourselves. When taking a conn from this pool, we want to obtain it`s remote ip and port .

**Comment by stephenandwood** [comment]
Wrap the connection with your own type that holds the address:

```
type myConn struct {
	redis.Conn
	address string
}
```
Wrap the connection returned from dial with that type:

```
func dial(network, address string, options ...redis.DialOption) (redis.Conn, error) {
	c, err := redis.Dial(network, address, options...)
	if err != nil {
		return nil, err
	}
	return myConn{c, address}, nil
}
```
Get the address from your connection like this:

```
func getAddress(c redis.Conn) string {
	mc, ok := c.(myConn)
	if ok {
		return mc.address
	}
	return ""
}
```

Alternatively, use `myConn` instead of `redis.Conn` throughout the application.

**Comment by itczl22** [comment]
> Wrap the connection with your own type that holds the address:
> 
> ```
> type myConn struct {
> 	redis.Conn
> 	address string
> }
> ```
> 
> Wrap the connection returned from dial with that type:
> 
> ```
> func dial(network, address string, options ...redis.DialOption) (redis.Conn, error) {
> 	c, err := redis.Dial(network, address, options...)
> 	if err != nil {
> 		return nil, err
> 	}
> 	return myConn{c, address}, nil
> }
> ```
> 
> Get the address from your connection like this:
> 
> ```
> func getAddress(c redis.Conn) string {
> 	mc, ok := c.(myConn)
> 	if ok {
> 		return mc.address
> 	}
> 	return ""
> }
> ```
> 
> Alternatively, use `myConn` instead of `redis.Conn` throughout the application.

I got it, thanks
