### ISSUE TITLE
Close hangs

### ISSUE THREAD

**Issue by ptman** [gomodule/redigo#456]
I have a problem with redis.Conn.Close() hanging on go 1.13.7. Please see testcase: https://gist.github.com/ptman/1c47b6a7fcb3ba2708a323a633dea95b

**Comment by ptman** [comment]
It doesn't hang when I'm stepping through using a debugger. So I ran it using -race:

```
WARNING: DATA RACE
Write at 0x00c0000a2248 by main goroutine:
  github.com/gomodule/redigo/redis.(*activeConn).Close()
      $GOPATH/src/github.com/gomodule/redigo/redis/pool.go:458 +0x8c
  main.main()
      $GOPATH/src/github.com/gomodule/redigo/redis/pubsub.go:58 +0x3fc

Previous read at 0x00c0000a2248 by goroutine 7:
  github.com/gomodule/redigo/redis.(*activeConn).Receive()
      $GOPATH/src/github.com/gomodule/redigo/redis/pool.go:542 +0x42
  github.com/gomodule/redigo/redis.PubSubConn.Receive()
      $GOPATH/src/github.com/gomodule/redigo/redis/pubsub.go:100 +0x42
  main.main.func2()
      $GOPATH/src/redistest/redistestcase.go:46 +0x86

Goroutine 7 (running) created at:
  main.main()
      $GOPATH/src/redistest/redistestcase.go:42 +0x33e

```

**Comment by ptman** [comment]
https://github.com/gomodule/redigo/blob/master/redis/pool.go#L458
https://github.com/gomodule/redigo/blob/master/redis/pool.go#L542

**Comment by ptman** [comment]
`Ctrl+\` (SIGQUIT) in the terminal when the test case blocks will conveniently print out the stack traces of all goroutines

**Comment by stephenandwood** [comment]
The [documentation says](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Concurrency):

> Connections support one concurrent caller to the Receive method and one concurrent caller to the Send and Flush methods. No other concurrency is supported including concurrent calls to the Do and Close methods.

The application calls Receive and Close concurrently which is not allowed.

Use one of the following approaches to cleanly close a pubsub receive loop:

- Send a QUIT command on the connection.
- Exit the loop when subscription count drops to zero. Unsubscribe all Redis channels on the connection.

**Comment by stevenh** [comment]
As stated above the code breaks the rules so that is invalid hence all bets are off

**Comment by ptman** [comment]
Do you have some suggestions or did I miss some example?

**Comment by stephenandwood** [comment]
I gave two suggestions in my previous comment.  The [pubsub example in the documentation](https://godoc.org/github.com/gomodule/redigo/redis#example-PubSubConn) illustrates the second of my suggestions.

**Comment by ptman** [comment]
Ah, I was reading the documentation of garyburd/redigo/redis, which doesn't mention Close under concurrency. Renames are tricky

**Comment by ptman** [comment]
Thank you for the patient guidance
