### ISSUE TITLE
v1.7.0 after v2.0.0, why?

### ISSUE THREAD

**Issue by bernardolm** [gomodule/redigo#459]
[v1.7.0](https://github.com/gomodule/redigo/commit/02dc2736dbc3a4a56907b0d5a9fead2f71b499db) released this on Jan 24, 2019

[v2.0.0](https://github.com/gomodule/redigo/commit/9c11da706d9b7902c6da69c592f75637793fe121) released this on Mar 15, 2018

v1.7.0 after v2.0.0, why?

**Comment by stevenh** [comment]
2.0 isn't actively developed I'm afraid see https://github.com/gomodule/redigo/pull/440 for some discussion on this.
