### ISSUE TITLE
how to use command "config get *"

### ISSUE THREAD

**Issue by ibm81** [gomodule/redigo#460]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

i will use code like this :
client, _ := redigo.Dial("tcp", host+":"+port)
_, err = client.Do("AUTH", password)
result, err := redigo.StringMap(client.Do("config get","dir"))

but some error response:
ERR unknown command `config get`, with args beginning with: `dir`

how to use command "config get *" ?

**Comment by oliver006** [comment]
Try separating all the words on the command and use `redigo.Strings`:

```
 result, err := redigo.Strings(client.Do("config", "get", "dir"))
```

**Comment by ibm81** [comment]
@oliver006
it's success,tks.
