### ISSUE TITLE
i have two redigo connected / passing info to each other 

### ISSUE THREAD

**Issue by gitmko0** [gomodule/redigo#462]
Possible to do a function of 
writeInterface(reply)

back?
so that the receiving side will not need to do a []byte to interface conversion.
If so, what's the optimum way to get it done? Can it be implemented as a standard function feature?

**Comment by stevenh** [comment]
I’m sorry but I don’t understand the question could you clarify what you’re trying to do?

**Comment by stevenh** [comment]
Closing due to no response, feel free to reopen if still needed.
