### ISSUE TITLE
Add DialContext function

### ISSUE THREAD

**Issue by 178inaba** [gomodule/redigo#475]
I want Context to be used when dialing.
So I want DialContext.

By default you should use Dialer.DialContext.
https://golang.org/pkg/net/#Dialer.DialContext

**Comment by stevenh** [comment]
Could you clarify why you want that?

**Comment by 178inaba** [comment]
I want to set the timeout using a Context like Dialer.DialContext.
This is because you can transparently set the timeout from upstream using Context.

**Comment by stevenh** [comment]
So to confirm my understanding you want for a pool to use the context passed into `GetContext(ctx)` to be passed through to any required `Dial`?

**Comment by 178inaba** [comment]
Yes!

I want to initialize the Pool as in the code below.

```go
func newPool(addr string) *redis.Pool {
  return &redis.Pool{
    DialContext: func(ctx context.Context) (Conn, error) { return redis.DialContext(ctx, "tcp", addr) },
  }
}
```
