### ISSUE TITLE
Pool.Get code can be simple

### ISSUE THREAD

**Issue by 178inaba** [gomodule/redigo#477]
The pull request #478 makes the code simple.

**Comment by stevenh** [comment]
Could you clarify what issue are you trying to solve?

**Comment by 178inaba** [comment]
I was reading the Redigo code and thought there was a part that could be simplified.
So I made a pull request.
That's the only reason.

If this issue should not be resolved, I agree to close it.

**Comment by stevenh** [comment]
That's a good goal.

My feedback would be there's no need for an issue in this case, happy for this to just be handled in a PR.
