### ISSUE TITLE
redis.Dial() return “EOF” error ! 

### ISSUE THREAD

**Issue by XiaoGe2030** [gomodule/redigo#484]
I use redigo.Dial() get 'EOF' error .  My code is as follows
```
c, err = redis.Dial("tcp", "xxx", redis.DialPassword("xx"),redis.DialConnectTimeout(time.Second*60))
if err != nil {
   fmt.Printf( "failed to connect to redis, error: %s", err.Error())
   return err
} 
......
```
As shown in the figure below 
![image](https://user-images.githubusercontent.com/22184388/82235935-f63a8b80-9965-11ea-9e2f-96051f1345e6.png)

I think it is caused by network instability .But I do n’t know how to handle this error.  When an EOF appears, should I ignore it and try again?

**Comment by stevenh** [comment]
Strange error, I would `tcpdump` to sessions if possible to see if there is more information.

**Comment by stevenh** [comment]
Closing due to no response, if this is still an issue feel free to reopen with more information.
