### ISSUE TITLE
github.com/gomodule/redigo/redis in multiple modules

### ISSUE THREAD

**Issue by techoner** [gomodule/redigo#485]
```
github.com/gomodule/redigo/redis: ambiguous import: found package github.com/gomodule/redigo/redis in multiple modules:
        github.com/gomodule/redigo v2.0.0+incompatible (/usr/local/go/workplace/pkg/mod/github.com/gomodule/redigo@v2.0.0+incompatible/redis)
        github.com/gomodule/redigo/redis v0.0.0-20200429221454-e14091dffc1b (/usr/local/go/workplace/pkg/mod/github.com/gomodule/redigo/redis@v0.0.0-20200429221454-e14091dffc1b)
```

**Comment by techoner** [comment]
@garyburd

**Comment by stevenh** [comment]
What version of go are you using there?
We recently enabled gomod support so you should be seeing v1.X versions not v2.X

**Comment by silenceper** [comment]
same issue

**Comment by fxk2006** [comment]
same issue

**Comment by silenceper** [comment]
same issue.

Because go.mod in my local project introduced a different version of redisgo.

**Comment by ppphp** [comment]
I met the same question, and it can be solved. Do not use `go get github.com/gomodule/redigo/redis` in the current README.markdown, and try using `go get github.com/gomodule/redigo`

`github.com/gomodule/redigo/redis v0.0.0-20200429221454-e14091dffc1b` is a wrong dependency, which is introduced in the [commit](https://github.com/gomodule/redigo/commit/e14091dffc1b085ace903ff7c41916e17c2daca3), and it was reverted [later](https://github.com/gomodule/redigo/commit/ac5712f8a62f2cabee489bd84282d2f0e738460a)

So the solution is to find dependency with `github.com/gomodule/redigo/redis` in some go.mod, delete it and use `github.com/gomodule/redigo` instead, which should be `github.com/gomodule/redigo v1.8.1` or something else.

**Comment by stevenh** [comment]
I can't reproduce this in a project which supports go.mod
```
> mkdir redis-test
> cd redis-test
> go mod init githib.com/stevenh/redis-test
go: creating new go.mod: module github.com/stevenh/redis-test
> go get github.com/gomodule/redigo/redis
go: downloading github.com/gomodule/redigo v1.8.1
go: found github.com/gomodule/redigo/redis in github.com/gomodule/redigo v1.8.1
```

**Comment by ppphp** [comment]
I have a different outcome
```
me@me:~/hobby/redis-test$ go mod init githib.com/stevenh/redis-test
go: creating new go.mod: module githib.com/stevenh/redis-test
me@me:~/hobby/redis-test$ go get github.com/gomodule/redigo/redis
go: finding github.com/gomodule/redigo/redis latest
me@me:~/hobby/redis-test$ cat go.mod 
module githib.com/stevenh/redis-test

go 1.13

require github.com/gomodule/redigo/redis v0.0.0-20200429221454-e14091dffc1b // indirect
```
The behaviour is same in go1.14.  It's very confusing.

**Comment by stevenh** [comment]
I think you may have a bad cache try `go clean -modcache` before.

```
~/tst$ go clean -modcache
~/tst$ go mod init githib.com/stevenh/redis-test
go: creating new go.mod: module githib.com/stevenh/redis-test
~/tst$ go get github.com/gomodule/redigo/redis
go: downloading github.com/gomodule/redigo v1.8.2
go: downloading github.com/gomodule/redigo/redis v0.0.0-do-not-use
go: found github.com/gomodule/redigo/redis in github.com/gomodule/redigo v1.8.2
~/tst$ more go.mod
module githib.com/stevenh/redis-test

go 1.14

require github.com/gomodule/redigo v1.8.2 // indirect
```

**Comment by stevenh** [comment]
Closing due to no response, feel free to reopen if this is still an issue
