### ISSUE TITLE
How to choose the redigo version

### ISSUE THREAD

**Issue by daheige** [gomodule/redigo#486]
Redigo currently has 1.8.1 and a 2.0.0 version, can these two versions do some explanations, such as what has been upgraded, which version is recommended for the production environment, because I see that 2.0.0 has not been updated at all , And the 1.8.x version of redigo has been updated.

**Comment by stevenh** [comment]
2.0 is old, it was created as a new feature set but didn't make much progress. It's only been kept for compatibility for those that tried it.

So in summary use 1.X (master) which is being actively supported.

**Comment by daheige** [comment]
Thanks, you mean 1.x version for production environment, right?

**Comment by stevenh** [comment]
Correct
