### ISSUE TITLE
The tag has not been updated

### ISSUE THREAD

**Issue by choyri** [gomodule/redigo#492]
Since the last tag v1.8.1 (6 May), some features and fixes have been added, but the tag has not been updated, such as v1.8.2, v1.8.3, why?
Because of this, I still get v1.8.1 with `go get`.
I see the `gomodule` in the organization's name, but it's not really perfectly supported. 😢

**Comment by stevenh** [comment]
Was just giving things a chance to settle will create a new release now

**Comment by stevenh** [comment]
https://github.com/gomodule/redigo/releases/tag/v1.8.2
