### ISSUE TITLE
a problem about pipelining

### ISSUE THREAD

**Issue by hzt1234hf** [gomodule/redigo#493]
I use pipeline to implement transactions (like this [https://godoc.org/github.com/gomodule/redigo/redis#hdr-Pipelining](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Pipelining) , but it not return error,all error values are nil
My redis data type and  code is as follows
- redis data type:
![image](https://user-images.githubusercontent.com/13149537/84612810-4a4c7780-aef4-11ea-9c20-87ec083122a9.png)

- code1:
```golang
if res, err := conn.Do("SMEMBERS", "test2"); err != nil {
	fmt.Printf("========error:\t%v\n", err) // Execute this line
} else {
	fmt.Println(res)
}
```
- output1:
![image](https://user-images.githubusercontent.com/13149537/84612901-90094000-aef4-11ea-8dea-648bc8788494.png)

- code2:
```golang
fmt.Println(conn.Send("MULTI"))
fmt.Println(conn.Send("SMEMBERS", "test2"))
res, err := conn.Do("EXEC")
if err != nil {
	fmt.Printf("========error:\t%v\n", err)
} else {
	fmt.Println(res) // Execute this line
}
```
- output2:
![image](https://user-images.githubusercontent.com/13149537/84613510-ed51c100-aef5-11ea-932a-9cf21c11b507.png)

how can i solve this problem?

**Comment by stevenh** [comment]
That's correct behaviour see [details on how transactions work](https://redis.io/topics/transactions)
