### ISSUE TITLE
Error when receiving data from __redis__:invalidate channel (redis 6)

### ISSUE THREAD

**Issue by math-nao** [gomodule/redigo#499]
When subscribing to `__redis__:invalidate` channel in order to manage [client side caching](https://redis.io/topics/client-side-caching) new feature on redis 6, an error occur when receiving data.

After running `SET foo bar` in another connection, message is received by subscriber but parsing message failed with this error:
`redigo.Scan: cannot assign to dest 1: strconv.ParseUint: parsing "foo": invalid syntax`

**Comment by stevenh** [comment]
It's not clear if this an internal redigo issue or an issue with your local code.

Could you provide a full example which demonstrates the issue @math-nao

**Comment by math-nao** [comment]
Not sure it is related to my local code (using redigo v1.8.2). When I subscribe to another channel and send data, everything works as expected.

**Comment by math-nao** [comment]
any news on this issue?

**Comment by stevenh** [comment]
Sorry I didn't spot your update. I can't see anywhere above which would give you the error you got, is there a bit missing?

**Comment by stevenh** [comment]
@math-nao any update on the error your seeing?

**Comment by stevenh** [comment]
closing due to no response
