### ISSUE TITLE
go.mod specifies go 1.14

### ISSUE THREAD

**Issue by eli-darkly** [gomodule/redigo#500]
I have a Go 1.13 project where I'd like to be able to use this module. I realize that the specification of `go 1.14` in your `go.mod` doesn't prevent me from doing this, and it does compile for me now— but doesn't this mean that the project _could_ add some code that would only compile in Go 1.14? Assuming that 1.13 is still supported for this module, it seems to me that the `go.mod` should ensure that that's definitely true by declaring itself as 1.13.

**Comment by stevenh** [comment]
It's something thats added automatically by the tool chain.

As you said you should be fine as we try to maintain compatibility as much as possible.

**Comment by eli-darkly** [comment]
I know it's added automatically by the tool chain, but if you want to ensure that you're maintaining Go 1.13 compatibility, the normal thing to do (as far as I know) is to either edit that line—since every line in `go.mod`, whether it was automatically generated or not, is meant to be editable—or simply to use Go 1.13 when you originally add module support, since the value it puts there is based on what version you're using at the time.

As [the tool documentation](https://golang.org/ref/mod#tmp_12) says, if you do that, you'll get an error if at some later time you accidentally use a language feature that's not supported in Go 1.13 and try to build your code.

I realize that your CI build is serving the same purpose by building the code in many versions. But the Go toolchain doesn't know about Travis builds, and it does know about `go.mod`... and when the language provides a feature like this, I think it's better to use it as intended rather than having it declare information that's not what you intend. Right now, what your `go.mod` file is telling people (and tools) is that they cannot count on it being Go 1.13 compatible.

I don't want to belabor this, but I wanted to make sure it was clear that "it's added automatically by the tool chain", in this case, is not a reason _not_ to change it. It's an editable declaration just like the dependencies, so you're making a choice to declare it this way.
