### ISSUE TITLE
这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接

### ISSUE THREAD

**Issue by mrwangchao** [gomodule/redigo#504]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
![image](https://user-images.githubusercontent.com/10059613/88248674-897c9e00-ccd4-11ea-9a34-b9e70a3996c7.png)
```go
func (p *Pool) put(pc *poolConn, forceClose bool) error {
	p.mu.Lock()
	if !p.closed && !forceClose {
		pc.t = nowFunc()
		p.idle.pushFront(pc)
		if p.idle.count > p.MaxIdle {
			pc = p.idle.back
			p.idle.popBack()
		} else {
			pc = nil
		}
	}

	if pc != nil {
		p.mu.Unlock()
		pc.c.Close()
		p.mu.Lock()
		p.active--
	}

	if p.ch != nil && !p.closed {
		p.ch <- struct{}{}
	}
	p.mu.Unlock()
	return nil
}
```

发现这里连接数过多时，如果一段时间 put操作获取到mu 就会阻塞GetContext获取连接。 被放回到空闲连接池里面的连接因为超过 MaxIdle 的限制，会被误回收

**Comment by mrwangchao** [comment]
实际线上验证，连接数过多时长连接的个数不稳定， 很多处于TIME_WAIT 状态的连接

**Comment by stevenh** [comment]
I’m not sure what you believe is an issue here, could be a google translate issue. Could you clarify?

**Comment by stevenh** [comment]
To clarify `MaxIdle` is the maximum number of idle connections not the maximum number of connections.

**Comment by mrwangchao** [comment]
Here the free connection pool is a valid connection pool, and when using a connection, a valid connection is directly taken from the free connection pool.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomodule/redigo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 凌晨2:28
收件人:&nbsp;"gomodule/redigo"<redigo@noreply.github.com&gt;;
抄送:&nbsp;"JIAN"<284843859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gomodule/redigo] 这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接 (#504)





 
To clarify MaxIdle is the maximum number of idle connections not the maximum number of connections.

**Comment by bensema** [comment]
> 实际线上验证，连接数过多时长连接的个数不稳定， 很多处于TIME_WAIT 状态的连接

试试`echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse`

**Comment by mrwangchao** [comment]
跟TIME_WAIT状态的连接是否可以重用没有关系的,&nbsp; 我们的MaxIdle设置太小了， 导致很多连接归还时被误以为空闲连接过多，主动释放连接了。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomodule/redigo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午5:23
收件人:&nbsp;"gomodule/redigo"<redigo@noreply.github.com&gt;;
抄送:&nbsp;"JIAN"<284843859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gomodule/redigo] 这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接 (#504)





  
实际线上验证，连接数过多时长连接的个数不稳定， 很多处于TIME_WAIT 状态的连接
  
试试echo 1 &gt; /proc/sys/net/ipv4/tcp_tw_reuse

**Comment by stevenh** [comment]
`MaxIdle` is configurable so you can set it to something that fits your use case.

**Comment by mrwangchao** [comment]
This is correct, but if the MaxIdle setting is very large, it is equivalent to not requiring the limitation of MaxIdle, and directly judging whether it needs to be recycled based on the idle time of the connection




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomodule/redigo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 凌晨0:58
收件人:&nbsp;"gomodule/redigo"<redigo@noreply.github.com&gt;;
抄送:&nbsp;"JIAN"<284843859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gomodule/redigo] 这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接 (#504)





 
MaxIdle is configurable so you can set it to something that fits your use case.

**Comment by stevenh** [comment]
If you choose to set very large you can and that would be similar to not specifying `MaxIdle` but I still don't know what you believe the issue is?

**Comment by mrwangchao** [comment]
Sorry, if MaxIdle is set very large, it can indeed be used as a shield. I just want to ask if MaxIdle is necessary. The current code on git is actually no problem




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomodule/redigo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 上午6:34
收件人:&nbsp;"gomodule/redigo"<redigo@noreply.github.com&gt;;
抄送:&nbsp;"JIAN"<284843859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gomodule/redigo] 这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接 (#504)





 
If you choose to set very large you can and that would be similar to not specifying MaxIdle but I still don't know what you believe the issue is?

**Comment by stevenh** [comment]
The use case for `MaxIdle` is if you have a system which has variable number of connections over time. For example it can be used to clean up connects after a spike in demand.

This is often important for systems which have multiple services which talk to a single redis instance where if all of those services where to spike over time it could result in very high connection numbers and hence performance numbers.

If you have a single app then it could be argued that there is no really need for except for house keeping.

**Comment by mrwangchao** [comment]
I get it, thank




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomodule/redigo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 上午6:32
收件人:&nbsp;"gomodule/redigo"<redigo@noreply.github.com&gt;;
抄送:&nbsp;"JIAN"<284843859@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gomodule/redigo] 这里是否可以去掉连接池长度限制,  空闲连接通过判断空闲时间长度来确定是否回收连接 (#504)





 
The use case for MaxIdle is if you have a system which has variable number of connections over time. For example it can be used to clean up connects after a spike in demand.
 
This is often important for systems which have multiple services which talk to a single redis instance where if all of those services where to spike over time it could result in very high connection numbers and hence performance numbers.
 
If you have a single app then it could be argued that there is no really need for except for house keeping.
