### ISSUE TITLE
Wrong number of arguments when pipelining with HMSET

### ISSUE THREAD

**Issue by kirebyte** [gomodule/redigo#506]
I can't seem to be able to do a proper HMSET without getting a  `ERR wrong number of arguments for 'hmset'` message. But I can do this manually.

What I'm trying to is to execute a set of pipelined commands in this order.

```
conn := pool.Get()
msg, err := conn.do("HGET", "config:"+config, "data1:data2:data3")
HmsetArgs := redis.Args{uid}
HmsetArgs = HmsetArgs.Add("something1", Something1)
HmsetArgs = HmsetArgs.Add("something2", Something2)
HmsetArgs = HmsetArgs.Add("something3", Something3)
conn.Send("HMSET", HmsetArgs...)
conn.Send("HINCRBY", uid, "foo", 0)
conn.Send("EXPIRE", uid, 1800)
conn.Send("RPUSH", Config+":foo:foo", uid)
msg, err := redis.MultiBulk(conn.Do(""))
if err != nil {
log.Error(err)
} else {
log.Info(msg)
}
```

**Comment by bpo** [comment]
@kirebyte that code snippet looks like it would work (provided variable definitions). Is it possible that in the code you're testing the `HmsetArgs.Add` lines never get called (e.g. are you running a loop over an empty slice)? If that guess is wrong you may need to share more details.

Printing/logging the value of `HmsetArgs` would be the quickest way to see what's going on.

**Comment by stevenh** [comment]
The "HMSET" is part of the args so you need:
```go
conn := pool.Get()
defer conn.Close()

args := redis.Args{"HMSET", uid}
// No real need for this to be an `Add` it could be just part of the constructor, just here as an example.
args = args.Add(
           "something1", Something1,
           "something2", Something2,
           "something3", Something3,
)
_ , err := conn.Send(args...)
if err != nil {
    log.Error(err)
    return
}
```
