### ISSUE TITLE
Struct support for Slice field

### ISSUE THREAD

**Issue by sreejumon** [gomodule/redigo#507]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

I have a struct similar to one given below, one of the field is of type Slice (Ranks)
```go
type Employee struct {
	      EmpID       int      `redis:"emp_id"`
	     Name        string   `redis:"name"`
	     Occupation  string   `redis:"occupation"`
	     Designation string   `redis:"designation"`
	    **Ranks       []string `redis:"ranks"`**
}
```
My requirement is to store these fields in the redis as a HSET and ranks field (Slice) concatenated with some concatenation String.

Can this requirement added to the existing package?

**Comment by stevenh** [comment]
You an achieve this by implementing https://godoc.org/github.com/gomodule/redigo/redis#Argument for your type
