### ISSUE TITLE
too many TIME_WAIT tcp conn

### ISSUE THREAD

**Issue by pysta3515** [gomodule/redigo#510]
the  source code in pool.get() ,it seems that when pool is full, and wait is true, new conn will be created rather than reuse old conn.

**Comment by stevenh** [comment]
Do you have an example of this, because if the pool is full and wait is true the request should block for a free connection. So there may be configuration miss understanding, which full example would show.

**Comment by pysta3515** [comment]
here is my test code and result:
`
var (
	pool *redis.Pool
)

func main() {
	InitPool()
	for i := 0; i < 100; i++ {
		go DO()
	}
	select {}
}

// InitPool ...
func InitPool() {
	pool = &redis.Pool{
		Dial:         func() (redis.Conn, error) { return redis.Dial("tcp", "127.0.0.1:6379") },
		TestOnBorrow: func(redis.Conn, time.Time) error { return nil },
		MaxIdle:      10,
		MaxActive:    50,
		IdleTimeout:  60,
		Wait:         true,
	}
}

// DO ...
func DO() {
	for {
		do()
	}
}

func do() {
	conn := pool.Get()
	defer conn.Close()
	_, err := redis.String(conn.Do("GET", "foo"))
	if err != nil {
		panic(err)
	}
}
`
after a moment the port exhausted and panic:
![image](https://user-images.githubusercontent.com/16321757/92572412-fbc23580-f2b6-11ea-8191-4f6d163bdb9c.png)

**Comment by pysta3515** [comment]
> Do you have an example of this, because if the pool is full and wait is true the request should block for a free connection. So there may be configuration miss understanding, which full example would show.
https://github.com/gomodule/redigo/issues/510#issuecomment-689403739
here is my test code and result:
```
var (
	pool *redis.Pool
)

func main() {
	InitPool()
	for i := 0; i < 100; i++ {
		go DO()
	}
	select {}
}

// InitPool ...
func InitPool() {
	pool = &redis.Pool{
		Dial:         func() (redis.Conn, error) { return redis.Dial("tcp", "127.0.0.1:6379") },
		TestOnBorrow: func(redis.Conn, time.Time) error { return nil },
		MaxIdle:      10,
		MaxActive:    50,
		IdleTimeout:  60,
		Wait:         true,
	}
}

// DO ...
func DO() {
	for {
		do()
	}
}

func do() {
	conn := pool.Get()
	defer conn.Close()
	_, err := redis.String(conn.Do("GET", "foo"))
	if err != nil {
		panic(err)
	}
}
```
after a moment the port exhausted and panic:
![image](https://user-images.githubusercontent.com/16321757/92572412-fbc23580-f2b6-11ea-8191-4f6d163bdb9c.png)

**Comment by pysta3515** [comment]
sorry, IdleTimeout field error. 60*time.Second
