### ISSUE TITLE
Junk value is returned on second time 

### ISSUE THREAD

**Issue by ssenthil416** [gomodule/redigo#511]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

Hi

I using your module for redis cache in my project.
I found this issue, here is my flow

> I SET the cache like this Key is "Test_<hashKey>" and Value is a structure with one of the filed in that is Error which is string to a null.
> I used GET to read this key "Test_<hashKey>", the Error still is null
> And I try to DEL this key "Test_<hashKey>"
First time it worked fine. But time when I try to do the same for second time
GET return Error value like this
"Exception: ACS SPV Error: While setting parameters for a speed test: com.netopia.nbbs.tr69.connreq.ConnectionRequestException: device.connreq.default.networkerror, 589630E562C3"

After DEL, do I need to clean up or sync. Please let me know.

**Comment by stevenh** [comment]
This module and golang as a language doesn't use Exceptions, so I think your using something else and not this library.

If you are using this library please post an code example and the exact error your seeing.

**Comment by ssenthil416** [comment]
Each time I get different error, here is one more
\"error\":\"iperf3 test timed out. Server reported (iperf process ended with code '1' and signal 'null' because it was killed.). Device reported ({\\\"message\\\"=\\u003e\\\"ACS GPV Error: While collecting results from device: com.netopia.nbbs.tr69.connreq.ConnectionRequestException: device.connreq.default.networkerror, 5C7695135CD4\\\"

**Comment by ssenthil416** [comment]
I tested with other go redis library and found the error, So I am closing this issue

**Comment by ssenthil416** [comment]
I tested with other go redis library and found the error, So I am closing this issue
