### ISSUE TITLE
Adding dial options into the Dial func on the Redigo Pool type

### ISSUE THREAD

**Issue by joseph-norman** [gomodule/redigo#514]
Hi all,

Forgive me if this has been asked before I was unable to find this under GitHub issues, but it looks like there is a gap between the `Dial` func and the Dialer that is supplied to the `Pool` type. Does it make sense to allow the Pool type handler to support Dial options, whenever a connection is established?

In my experience, pools are used to ensure we have hard limits on connections particularly when scaling. It would be great to supply dialing options for these connections, too (such as timeouts). Thanks!

**Comment by stevenh** [comment]
You can make `Dial func() (Conn, error)`  use what ever `DialOption` you need its just a function e.g.
```go
p := redis.Pool {
   Dial: func() (redis.Conn, error) {
      return redis.Dial("tcp", ":6379", redis.DialConnectTimeout(time.Second))
   }
}
defer p.Close()
....
```

**Comment by joseph-norman** [comment]
Sure that would remove the need for this, I'm more asking if its something that should be considered as part of the design of the `Pool` type.

**Comment by stevenh** [comment]
That would be less flexible than the current solution, so unless I'm missing something I don't see the need to complicate pool implementation?

**Comment by joseph-norman** [comment]
Thanks, that makes sense
