### ISSUE TITLE
Can it be embedded into the system to implement package calls？

### ISSUE THREAD

**Issue by Matthewbalala** [gomodule/redigo#517]
Hello, I hope to embed the redis solution into my system. I don't want to use the tcp protocol. I hope to implement the way to call redigo lib. Don't know redis support?

**Comment by stevenh** [comment]
Not sure what you're really asking there @Matthewbalala but it sounds like a usage question not bug which is what issues are for, so I would recommend asking the question over at something like stackoverflow.
