### ISSUE TITLE
huge size keys of HMGET

### ISSUE THREAD

**Issue by yanan-xu** [gomodule/redigo#518]
I'm using HMGET to fetch a batch of keys, it's about 10,000,000,
then occurred this error: 
```Recovered panic error: %!(EXTRA *net.OpError=write tcp [::1]:52400->[::1]:6379: write: broken pipe)```

i think it's caused by I sending too much bytes, want to know:
- what's the limitation of this `conn.Do(HMGET)` (timeout or bytes size)
- is there any to to upgrade this limitation
- is there any other way to solve this besides split to batch requests

**Comment by stevenh** [comment]
There shouldn't be any limitation, the error being a write error to the redis server I would check it's logs to see what caused the failure.

That said `HMGET` only operates on a single key not a "batch of keys" so it might be good to clarify what exactly you're doing there.

**Comment by yanan-xu** [comment]
just to clarify, a batch of fields on one key: e.g. `HMGET mykey field1 field2...`
more info:
seems the `conn.Do` func can only receive 1024 * 1024 args, include the command itself. So I can get  (1024 * 1024 - 2) fields, one more field will cause this error.

**Comment by stevenh** [comment]
I don't see anything in the library which has such a limitation.

Have you tried doing the same command using the redis cli to see if its actually redis protocol limitation?

**Comment by stevenh** [comment]
I would also suggest that doing such a request is likely not good idea and you should look at what changes you could make to your data structure or app to avoid such call.

**Comment by yanan-xu** [comment]
I used a python library and that works.

Yes I realized that this is't a best practice of using Redis,  I looked back to the story and find a good way to avoid this operation, now only need to fetch one single filed now.
thanks for your suggestion

**Comment by stevenh** [comment]
Interesting I wonder where that limits is coming from.

From a performance stand point you might want to consider getting multiple at a time.

Also have you considered HGETALL?

**Comment by yanan-xu** [comment]
oh my bad, sorry to misleading you.
> I used a python library and that works.

in fact python also have the same issue, so I think it's limited on Redis side(but not confirm).

**Comment by stevenh** [comment]
Thanks for update @yanan-xu looks like there are some limits in redis itself, not sure what you're hitting but I did find [this stackoverflow article](https://stackoverflow.com/questions/42911672/is-there-any-limit-on-the-number-of-arguments-that-redis-commands-such-as-zadd-o#:~:text=The%20maximum%20number%20of%20arguments,long%20meaning%20up%20to%202%2C147%2C483%2C647.)

Let me know if you're OK to close this issue out if you think its not a library issue?
