### ISSUE TITLE
Whether to support batch iteration of information between two key values？

### ISSUE THREAD

**Issue by Matthewbalala** [gomodule/redigo#519]

**Comment by stevenh** [comment]
@Matthewbalala that doesnt give us enough information to answer you question. Could you clarify what problem your seeing with this library? 

If its not a bug and more a question how to use then I'm afraid this isn't for forum for those types of questions.

**Comment by konoleoda** [comment]
+1

**Comment by Matthewbalala** [comment]
I uploaded a lot of data in the database. I don’t know whether redigo supports this situation: I know the two key values in the database, can I  iterate all the keys between the two key values (start key and end key) or data.

**Comment by stevenh** [comment]
Sorry without any information on the data you’re referring it’s impossible to answer

**Comment by stevenh** [comment]
Closing due to no response
