### ISSUE TITLE
[Go redigo]   MaxActive / wait may not work, thousands of connections are still being created

### ISSUE THREAD

**Issue by johnzheng1975** [gomodule/redigo#534]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

[Go redigo] MaxActive / wait may not work, thousands of connections are still being created.

Go version: 1.14 
github.com/gomodule/redigo v2.0.0+incompatible

Step 1: Wrote code as below, wait is true, maxActive is 99. 
Step 2: Deploy the container in k8s. Doing load testing
Step 3: Using `netstat -nat | grep 6379 | wc -l`, you can find the connection all more than maxActive for each pod.
```
# netstat -nat | grep 6379 | wc -l
xxbp-blacklist-6c9fcb57f4-66jpw
2897
xxbp-blacklist-6c9fcb57f4-6pdrp
12853
xxbp-blacklist-6c9fcb57f4-9kpjs
252
xxbp-blacklist-6c9fcb57f4-hkwj7
165
```
Step 4, In aws elasticache redis server monitoring tool, you can find the connections go up to 10000 totally. {Expected: less than 1000}

Code --redisutil.go--
```
package redisutil

import (
    "AuthService/config"
    "context"
    "fmt"
    "github.com/gomodule/redigo/redis"
    "log"
    "time"
)

var pool *redis.Pool

func InitializeRedisPool() error {
    conf := config.GetConfig()
    conf.AutomaticEnv()
    pool = &redis.Pool{
        MaxIdle:     10,
        MaxActive:   99,
        Wait:        true,
        IdleTimeout: 240 * time.Second,
        Dial: func() (redis.Conn, error) {
            c, err := redis.Dial("tcp",
                conf.GetString("redis_host"),
                redis.DialPassword(conf.GetString("redis_token")),
                redis.DialTLSSkipVerify(conf.GetBool("redis_tlsskipverify")),
                redis.DialUseTLS(conf.GetBool("redis_usetls")))
            if err != nil {
                log.Fatalln("Redis error during connect! " + conf.GetString("redis_host") +
                    " redis_token" + conf.GetString("redis_token") +
                    " redis_tlsskipverify:" + conf.GetString("redis_tlsskipverify") +
                    " redis_usetls:" + conf.GetString("redis_usetls"))
                log.Fatalln(err)
                return nil, err
            } else {
                return c, nil
            }
        },
    }

    //Check whether conn can be set up correctly
    conn, err := pool.GetContext(context.Background())
    if err != nil {
        return err
    }
    defer conn.Close()
    return nil
}
 

func VerifyBlacklist(token string) bool {
    conn := pool.Get()

    defer conn.Close()

    exists, err := redis.Bool(conn.Do("EXISTS", "blacklist:"+token))
    if err != nil {
        // handle error return from c.Do or type conversion error.
        log.Println("Redis error: error return from c.Do or type conversion error.")
        log.Println(err)
        return false //Use this temporally, friend for testing
    }

    return exists
}
```

-- code main.go ---
```
    err := redisutil.InitializeRedisPool()
    if err != nil {
        log.Print("Redis error! InitializeRedisPool Fail!")
    }
```

-- API will call redisutil.VerifyBlacklist, note that this api will be invoked 100000 times during load testing ---

Expected Result: 
With command `netstat -nat | grep 6379 | wc -l`, connections should less than 99 for each pod.

Actual Result:
The connections is arrive 12853 during load testing~

**Comment by johnzheng1975** [comment]
Ok, I am using "netstat -nat | grep 6379 | grep ESTABLISHED | wc -l", almost all pods' connection is 20 exactly. 
However, my maxActive is 99.
Which maxActive impact?  
"netstat -nat | grep 6379  | wc -l"?  If so, why one pod value arrive 3469?
"netstat -nat | grep 6379 | grep ESTABLISHED | wc -l" ? If so, why pod connections valueis 20, not 99? (I am sure the the load is very heavy )

npcore@ip-172-20-223-79:~$ export ns=xxbp-dev-public;kubectl get pods -n $ns|grep blacklist|awk '{print $1}'|xargs -i sh -c "echo {};kubectl exec {} -c istio-proxy -n $ns --  netstat -nat | grep 6379  | wc -l" 
xxbp-blacklist-75495f4b87-2xx6j
22
xxbp-blacklist-75495f4b87-8gn2m
36
xxbp-blacklist-75495f4b87-99n2z
20
xxbp-blacklist-75495f4b87-j4kdc
40
xxbp-blacklist-75495f4b87-l4wd6
86
xxbp-blacklist-75495f4b87-ldcc7
3469
xxbp-blacklist-75495f4b87-nzzvv
20
xxbp-blacklist-75495f4b87-rfdfs
34
xxbp-blacklist-75495f4b87-wnfx5
56
xxbp-blacklist-75495f4b87-xlwwj
36
npcore@ip-172-20-223-79:~$ export ns=xxbp-dev-public;kubectl get pods -n $ns|grep blacklist|awk '{print $1}'|xargs -i sh -c "echo {};kubectl exec {} -c istio-proxy -n $ns --  netstat -nat | grep 6379 | grep ESTABLISHED | wc -l" 
xxbp-blacklist-75495f4b87-2xx6j
20
xxbp-blacklist-75495f4b87-8gn2m
20
xxbp-blacklist-75495f4b87-99n2z
20
xxbp-blacklist-75495f4b87-j4kdc
20
xxbp-blacklist-75495f4b87-l4wd6
20
xxbp-blacklist-75495f4b87-ldcc7
20
xxbp-blacklist-75495f4b87-nzzvv
20
xxbp-blacklist-75495f4b87-rfdfs
20
xxbp-blacklist-75495f4b87-wnfx5
20
xxbp-blacklist-75495f4b87-xlwwj
20

**Comment by johnzheng1975** [comment]
Since I am using AWS elasticache redis, I talked with AWS support.
He thought my connection pool does not work, because "new connections" of AWS redis is arrived 10000. But "curr connections" of AWS redis is only 280.
So, can anyone check why redigo connections not work? Any error configure? Thanks.

**Comment by johnzheng1975** [comment]
The issue is resolved after I change maxidle to 100. 
The netstat -nat | grep 6379 |grep ESTABLISHED| wc -l highest value is 200. (Previous it is 20) 
The netstat -nat | grep 6379 |grep WAIT| wc -l is not much. (Previously it is more than 10000) 

This is interesting maxIdle impacts maxActive, and the real active connections is 2 times of maxIdle, could I know why? Thanks.

**Comment by stevenh** [comment]
Could you try the latest release https://github.com/gomodule/redigo/releases/tag/v1.8.3 which does include a fix for incorrect counts.

**Comment by stevenh** [comment]
@johnzheng1975 did you manage to try v1.8.3?

**Comment by Gerrard-YNWA** [comment]
@johnzheng1975  I think thousands of TIME_WAIT connections was as expected.  

Here is my understanding. The `MaxActive` specifies the max connections number  allocated by the pool is 99, and the `MaxIdle` indicates the max connections keeps ESTABLISH state in the pool is 10, Once the connection number in the pool larger than `MaxIdle`,  the pool will close connections to satisfy the `MaxIdle` connection number. These closed connections will change state to TIME_WAIT due to the tcp four way handshake termination.

When changes the `MaxIdle` same as `MaxActive` ,  the pool holds the `MaxActive` connection count always equal to `MaxIdle` and there is no need for the pool to close any connections.

**Comment by stevenh** [comment]
Based on the above I'm going to close this issue. Feel free to reopen if you think it's still a valid issue.
