### ISSUE TITLE
Does it reconnect After redis server restart?

### ISSUE THREAD

**Issue by chy9003** [gomodule/redigo#543]
Does it reconnect After redis server restart?

**Comment by chy9003** [comment]
I want to used it in my own project?
but i don't know this package supports reconnect after redis server restart?
if supported, how to config?
ths

**Comment by HeCorr** [comment]
The recommended way to achieve this is by using connection pools, as explained here:  https://stackoverflow.com/a/24388551

If you want a more complete code with AUTH (if you have it enabled) and automatic PING on borrow: https://gist.github.com/HeCorr/1cb443233874b7a5d037b95f11cb96da
