### ISSUE TITLE
RESP3 and client side caching support

### ISSUE THREAD

**Issue by WideLee** [gomodule/redigo#546]
client side caching and redis protocol RESP 3 is released in Redis version 6.0, is any plan to support them in `redigo` library? 

https://github.com/antirez/RESP3/blob/master/spec.md
https://redis.io/topics/client-side-caching

**Comment by stevenh** [comment]
There is a PR for this: https://github.com/gomodule/redigo/pull/521 which I haven't had chance to look at.

If you're interested in this feature, please take a look and provide feedback

**Comment by WideLee** [comment]
> There is a PR for this: #521 which I haven't had chance to look at.
> 
> If you're interested in this feature, please take a look and provide feedback

Perfect, I'll close this issue and take a look at that PR, thank you :smile:
