### ISSUE TITLE
Receiving EOF from redis when subscribing to a channel

### ISSUE THREAD

**Issue by YuvalPruss** [gomodule/redigo#547]
Redis has some sort of timeout after 1hr, which raises EOF error when I'm subscribing to some channels.
My Code:

```
pubsub := redis.PubSubConn{Conn: rc}
events := ["controller"]
err = pubsub.Subscribe(events)
if err != nil {
      return
}
for {
    switch v := pubsub.Receive().(type) {
     case error:
        log.Printf("Error: %v", v)
         return
     case redis.Message:
          ...
```

And each hour I see this in the logs (which cause my service to crash):
```
Error: EOF
```

Why do I always receive this `EOF` message? Should I set some kind of a timeout somewhere?

Versions:
Redis docker => redis:6.0.9-alpine (no redis.conf)
redigo => v1.8.3

**Comment by stevenh** [comment]
Sounds like a network event I would check to see if it corresponds with the server `timeout` e.g. `config get timeout` if so this could be a bug in your version of the linux server.

Alternatively it could be OS level setting impacting this for example a firewall or NAT.

Either way you're likely want to handle connections going way by getting a new connection from pool.

**Comment by stevenh** [comment]
Closing due to no response. Feel free to reopen if this is still an issue.
