### ISSUE TITLE
Custom type with String() method overrides Flat() output

### ISSUE THREAD

**Issue by dzvancuks** [gomodule/redigo#548]
When using custom type with String method it causes `strconv.ParseUint` error on Scan.

Let's assume there is following type override for uint8
```
type MyType uint8
func (mt MyType) String() string {...} // Helper for various printfs

type MyStruct struct {
	MyField             MyType        `redis:"MyField"` 
}
```

Calling `redis.Args{}.AddFlat(myStructInstance)` automatically converts MyField into string representation. As result Scan() cannot convert string value back to uint8 representation.
Removing String() solves this issue.

Is there a way to force usage of underlying type instead of converting it into string? Any other workarounds?

**Comment by stevenh** [comment]
You can solve this by implementing `Argument` in `MyType` e.g.
```go
func (mt MyType) RedisArg() interface{} {
    return uint8(mt)
}
```
