### ISSUE TITLE
Feature suggesion: transparent retries

### ISSUE THREAD

**Issue by rsheasby** [gomodule/redigo#550]
Not sure if this is out of redigo's stated scope, but it would be super handy to have automatic, transparent retrying for failed requests. It's the sort of thing that's messy to implement many times, and although it's definitely possible to extend it ourselves, it's always nice to have everything you need in one library.

I definitely wouldn't suggest it be default behaviour; maybe it shouldn't even be a config option but rather a new function entirely like `DoWithRetry`

**Comment by stevenh** [comment]
I understand this would be useful but it the retry policy would be highly reliant on what the app wanted including what to do with errors where there is no way to tell if the operation completed but the return of the result failed.

Given this I think this is best left to the client and not part of the core library.

**Comment by willspense** [comment]
I think there would be ways for the client to pass through what it wanted around retry parameters (context for instance) for such a function. Isn't the point of the retry to only handle errors on the operation itself?
Thanks.

**Comment by stevenh** [comment]
Unfortunately it's almost impossible to handle all the edge cases. Processed request but response not received particularly comes to mind.

Given this I don't think the package to could be expected to pick the right behaviour for each use case unfortunately.
