### ISSUE TITLE
brpop list but return err=EOF

### ISSUE THREAD

**Issue by wangxiangjun88** [gomodule/redigo#553]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis
for{
     res,err:=conn.Do("brpop","list",1000)
     ...... 
}
sometimes the err=io.EOF then message is lost, I don,t know if the res is nil ? so what should I do when i encounter this problem?

**Comment by stevenh** [comment]
As per the link please ask questions over at stackoverflow, this is for bugs with the library only, not usage questions I'm afraid.

That said investigate anything in your stack which may be causing the connection with redis to fail, as this shouldn't happen.
