### ISSUE TITLE
problem about pipeline

### ISSUE THREAD

**Issue by bluesky1024** [gomodule/redigo#558]
the choices between pipeline and multi parallel single req is hard for me. Here is my probelm.

the common use of "pipeline" is as follows
```go
func GetMultiRes(){
  conn := NewConn()
  // the key point of my problem
  defer conn.Close()
  
  conn.Send(cmd1,args...)
  conn.Send(cmd2,args...)
  conn.Flush()
  
  for i:0;i<2;i++{
      conn.Receive()
  }
}
```
what's more, the receive is required in explicit order as the same as send, Which mean the conn could not be shared in multi 
GetMultiRes func calls.

the use of pipeline cause addition time expenses to build connection in every req while multi parallel single req could be finished in connect pool. 

Is there any possibility that multi parallel single req is more efficient than pipeline? Or Do I misunderstand the use of pipeline?Anyway,  it puzzles me for a while... 

Thanks for your attention and reply very much...

**Comment by stevenh** [comment]
Unfortunately this forum is for issues aka bugs in the library and not for discussions about how to use it I'm afraid, those types of questions can be asked in other areas such as https://stackoverflow.com/
