### ISSUE TITLE
Consider blocking on request for connection from pool when exhausted

### ISSUE THREAD

**Issue by pkieltyka** [gomodule/redigo#56]
Presently, if a connection from a pool is requested with `pool.Get()` and the number of connections active has reached `MaxActive` then Get() will return the error `errPoolClosed`.

I feel its more expected by the application developer to always get a connection when calling pool.Get() -- unless the server is down or something. If a function needs to get/set data to redis, then it needs to do that, if the pool is exhausted because of high load on the application, then should it just keep looping asking for a connection until it's not exhausted anymore?

Perhaps having an async (as it is now) and sync Get() for requesting a connection.. like: `pool.Get()` to be synchronous and `pool.GetOrFail()` as async. Perhaps the sync Get() should also return an error after X time of waiting. `pool.Get(&redis.Wait{5})` .. and a default config option on the pool struct.

I wonder how application developers are using redigo's Pool{} stuff, I can imagine most are leaving MaxActive as 0 and just hoping the max number of connections on their system or server never hits. Considering that, there should be a default for `MaxActive`, not infinity. And `MaxIdle` should be some reasonable number as well. I wonder how other database drivers do it...? ie. database/sql.

I think it keeps it much simpler and expected for the app developer. At least for me..

**Comment by fjjiaboming** [comment]
<pre>
<code>
type Pool struct {
    MaxWaitTimeInMS time*Millisecond
    P *redis.Pool
}

func (p Pool) Get() Conn {
    var wait time.Time
    start := time.Now()
try_loop:
    for{
        c := p.P.Get()
        wait = time.Now().Sub(start)
        err := rcon.Err()
        switch err := c.Err() {
        case ErrPoolExhausted:
                {
                          if  wait  > ( time.Duration(p.MaxWaitTimeInMS) * time. Millisecond ) {
                                  break try_loop
                          }
                          // TODO chan implements.
                          time.Sleep(time.Duration(wait) * time.Millisecond)
                          continue
                }
        case nil: 
                {
                          return Conn{c};
                }
        default: 
                return err; 
        } // end switch
    } // end loop
}
</code>
</pre>

Why not to support  implementing blocking with timeout and other features  In Redigo ?

**Comment by garyburd** [comment]
@fjjiaboming Please open a new issue for timeout and other features.
