### ISSUE TITLE
redisx.ConnMux broken pipe recovery

### ISSUE THREAD

**Issue by mitchsw** [gomodule/redigo#569]
I am using a `redisx.ConnMux` to connect to a local Redis process over a Unix socket. If the Redis process restarts for any reason, the ConnMux begins failing with:

```
write unix @->/var/run/redis/redis.sock: write: broken pipe
```

This error condition is permanent. Even when the Redis process is running again, the ConnMux never attempts to reopen a new connection. This is in contrast to a `redis.Pool`, which I understand replaces broken connections.

I am working around this by crashing my Go binary whenever the pipe is broken, but of course a more graceful reconnection would be preferred.

Thank you!

**Comment by stevenh** [comment]
Package redisx contains experimental features for redigo. I wouldn't recommend using this package and would instead see if you can use just redis instead.
