### ISSUE TITLE
ScanStruct unexpected behaviour on types aliased from []byte

### ISSUE THREAD

**Issue by niallnsec** [gomodule/redigo#570]
Hello,

I noticed an issue recently when trying to store and retrieve a struct from Redis which contained several fields of type net.IP. I am using Args{}.AddFlat to store and ScanStruct to retrieve the data from Redis.

The net.IP type implements the stringer interface and so is stored (correctly, I would argue) as a string representation of the IP address. When the data is retrieved however, the string data is inserted directly into the net.IP buffer because ScanStruct thinks it is looking at a byte slice.

Initially I wanted to fix this with something like the following modification to scan.go:
```go
var ipType = reflect.TypeOf(net.IP{})

func convertAssignBulkString(d reflect.Value, s []byte) (err error) {
	switch d.Type().Kind() {
	case reflect.Slice:
		if d.Type() == ipType {
			ip := net.ParseIP(string(s))
			if ip == nil {
				 err = cannotConvert(d, s)
			} else {
				if v4 := ip.To4(); v4 != nil {
					ip = v4
				}
				d.Set(reflect.ValueOf(ip))
				break
			}
		}
		// Handle []byte destination here to avoid unnecessary
		// []byte -> string -> []byte converion.
		if d.Type().Elem().Kind() == reflect.Uint8 {
			d.SetBytes(s)
		} else {
			err = cannotConvert(d, s)
		}
                ...
```

That works well for IP addresses but I think there may be a deeper issue when you consider another arbitrary type which is an alias of []byte and also implements the stringer interface. That would result in the same divergent behaviour between the storing and retrieval of the data.

I can see in the documentation for ScanStruct that complex types like net.IP are not actually supported, but the function does not explicitly reject unsupported types when scanning into a struct which could result in unpredictable behaviour in other go programs.

None of this behaviour is explicitly incorrect, but I do think it creates a large foot gun which could very easily go unnoticed. For my specific problem I ended up implementing the RedisScan interface for an aliased net.IP type.

I am creating this issue mainly to seek your opinion on the above, and the possibility of either explicitly supporting some common stdlib types like net.IP or modifying ScanSruct to reject aliased types. I can imagine some cases where the current behaviour would be useful and could simplify retrieving data, so changing it could result in unexpected breakages of peoples code.

Thanks

**Comment by stevenh** [comment]
Hey @niallnsec could you provide an example of the problem?

**Comment by niallnsec** [comment]
Sure, here is an example.

I created two main routines so you could see the issue even without a redis server available.

<details>
  <summary>Example Code</summary>
  
  ```go
package main

import (
	"fmt"
	"net"

	"github.com/gomodule/redigo/redis"
)

type ipS struct {
	Addr net.IP
}

func main() {
	var ipStruct ipS
	ipStruct.Addr = net.ParseIP("10.0.1.1")

	conn, err := redis.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}

	_, err = conn.Do("HMSET", redis.Args{}.Add("some_key").AddFlat(&ipStruct)...)
	if err != nil {
		panic(err)
	}

	var vals []interface{}
	vals, err = redis.Values(conn.Do("HGETALL", "some_key"))
	if err != nil {
		panic(err)
	}

	var ipStructAfter ipS
	err = redis.ScanStruct(vals, &ipStructAfter)
	if err != nil {
		panic(err)
	}
	
	fmt.Println(ipStructAfter.Addr) //Prints "?31302e302e312e31"
}

func main_no_redis() {
	var ipStruct ipS
	//The string "10.0.1.1" gets stored in redis when using AddFlat so use it here
	err := redis.ScanStruct([]interface{}{[]byte("Addr"), []byte("10.0.1.1")}, &ipStruct)
	if err != nil {
		panic(err)
	}

	fmt.Println(ipStruct.Addr) //Prints "?31302e302e312e31"
}

  ```
</details>

**Comment by stevenh** [comment]
You can workaround this by using the following:
```go
type ipS struct {
        Addr addr
}

type addr struct {
        net.IP
}

func (t *addr) RedisScan(src interface{}) error {
        fmt.Println("here", t)
        if t == nil {
                return errors.New("nil pointer")
        }

        switch src := src.(type) {
        case string:
                return t.UnmarshalText([]byte(src))
        case []byte:
                return t.UnmarshalText(src)
        default:
                return fmt.Errorf("cannot convert from %T to %T", src, t)
        }
}
```

Does that help?

**Comment by stevenh** [comment]
@niallnsec did the above fix your issue?

**Comment by zuoshuwen** [comment]
> You can workaround this by using the following:
> 
> ```go
> type ipS struct {
>         Addr addr
> }
> 
> type addr struct {
>         net.IP
> }
> 
> func (t *addr) RedisScan(src interface{}) error {
>         if t == nil {
>                 return errors.New("nil pointer")
>         }
> 
>         switch src := src.(type) {
>         case string:
>                 return t.UnmarshalText([]byte(src))
>         case []byte:
>                 return t.UnmarshalText(src)
>         default:
>                 return fmt.Errorf("cannot convert from %T to %T", src, t)
>         }
> }
> ```
> 
> Does that help?

Hey @stevenh, It works fine, Thanks a lot.
