### ISSUE TITLE
reply.go sliceHelper does not handle Redis errors within the slice

### ISSUE THREAD

**Issue by mitchsw** [gomodule/redigo#579]
I have the following line of code:

```
values, err := redis.ByteSlices(conn.Do("MGET", params...))
```

Today I investigated the following error:

```
redigo: unexpected element type for ByteSlices, got type redis.Error
```

This error was very surprising! It comes from [here](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/reply.go#L321), which suggests that the `conn.Do()` reply [was indeed a interface{}[]](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/reply.go#L260), however one of the elements in the interface slice was a `redis.Error`.

This is technically possible based on RESP. You can have a [RESP array](https://redis.io/topics/protocol#resp-arrays) where one of the elements is a [RESP error](https://redis.io/topics/protocol#resp-errors). In redigo, this would hit [this readReply](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/conn.go#L654) for the array, and [this readReply](https://github.com/gomodule/redigo/blob/72af8129e040d6f962772a8c582e5e9f22085788/redis/conn.go#L628) for the inner error. Such a response is poorly handled by `sliceHelper`.

This likely hasn't been seen before because a normal `MGET` etc would never reply with a slice where one element is an error. However, when using the [Envoy Redis proxy](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/redis) with a partitioned cluster, this is possible if one of the endpoints is unavailable. I have quickly reproduced this with:

**Redis partition 1/3:**
```
127.0.0.1:6379> CLIENT PAUSE 60000 ALL
OK
```

**Envoy Redis proxy:**

```
127.0.0.1:6379> MGET a b c d e f g h i j k l m n o p
 1) (nil)
 2) (nil)
 3) (nil)
 4) (nil)
 5) (error) upstream failure
 6) (error) upstream failure
 7) (error) upstream failure
 8) (error) upstream failure
 9) (nil)
10) (nil)
11) (error) upstream failure
12) (error) upstream failure
13) (nil)
14) (nil)
15) (nil)
16) (nil)
(3.60s)
```

This reply will trigger the strange error message I saw above.

I think redigo could better handle this failure mode by propagating at least one of the array errors to the caller, e.g.:

```
redigo: slice contained an error: upstream failure
```

**Comment by stevenh** [comment]
Seems like the `upstream failure` was propagated, so could you clarify how you think this could be handled better?

**Comment by mitchsw** [comment]
Thanks for the reply @stevenh. The return value of

```
values, err := redis.ByteSlices(conn.Do("MGET", params...))
```

was

```
nil, Error("redigo: unexpected element type for ByteSlices, got type redis.Error")
```

So no, redigo didn't propagate the `upstream failure`, instead the library just told me there was an error without shedding light on what error it was. It also manifests as more of an internal "unexpected" error, when in fact the response was a valid reply.

It could be handled better by maybe just propagating the first error, e.g.

```
nil, Error("upstream failure")
```

or some kind of annotation, e.g.

```
nil, Error("redigo: slice contained an error: upstream failure")
```

**Comment by stevenh** [comment]
Thanks for clarifying @mitchsw!

**Comment by stevenh** [comment]
Can you try https://github.com/gomodule/redigo/pull/580 @mitchsw and see if that addresses the issue?

**Comment by stevenh** [comment]
Just checking in to see if you have managed to test #580 yet @mitchsw ?
