### ISSUE TITLE
Int64() failed when redis return large number

### ISSUE THREAD

**Issue by MakDon** [gomodule/redigo#581]
when using `ZINCRBY` to incr a large number , redis returns something like `4e+17`, which causes `Int64(reply interface{}, err error)` failed cause "invalid syntax"

```bash
host:port> ZINCRBY keytmp 100000000000000000 foobar
"4e+17"
```

Go code:

```Go
func TestParseInt(t *testing.T) {

	redisPool := &redis.Pool{
		Wait:        true,
		Dial: func() (redis.Conn, error) {
			con, err := redis.Dial("tcp", host + ":" + port, redis.DialPassword(password))
			if err != nil {
				return nil, err
			}
			return con, nil
		},
	}
	b, e := redisPool.Get().Do("ZINCRBY", "keytmp", 100000000000000000, "foobar")
	i, err := redis.Int64(b, e)
	fmt.Println(i, err) // output: 0 strconv.ParseInt: parsing "3e+17": invalid syntax
}
```

**Comment by FZambia** [comment]
Hello, according to [Redis Docs](https://redis.io/commands/ZINCRBY#return-value) about return value for ZINCRBY:

>  Bulk string reply: the new score of member (a double precision floating point number), represented as string.

So you should use `redis.Float64` I suppose.

**Comment by MakDon** [comment]
> Hello, according to [Redis Docs](https://redis.io/commands/ZINCRBY#return-value) about return value for ZINCRBY:
> 
> > Bulk string reply: the new score of member (a double precision floating point number), represented as string.
> 
> So you should use `redis.Float64` I suppose.

Thanks very much and sorry for my mistake.
