### ISSUE TITLE
Use command "LLEN" to return "QUEUE", I want int type

### ISSUE THREAD

**Issue by booldesign** [gomodule/redigo#583]
llen, err := rds.Do("LLEN", key)
fmt.Println(llen, err) // QUEUED <nil>

**Comment by booldesign** [comment]
上海二:15>LLEN listsize
"9"

**Comment by stevenh** [comment]
This isn't a issue, this is a usage questions, which should be asked in forums like [stackoverflow.com](stackoverflow.com)

If you want an int [see the documentation](https://pkg.go.dev/github.com/gomodule/redigo/redis#Int)

**Comment by booldesign** [comment]
I see, in the redis transaction(MULTI/EXEC), reply return "QUEUE"，sorry
