### ISSUE TITLE
Consider `retract` for v2 lineage

### ISSUE THREAD

**Issue by nelz9999** [gomodule/redigo#585]
As of Go 1.16, there is now a `retract` directive in the module system.

From my quick-ish reading of things (https://go.dev/ref/mod#go-mod-file-retract), it seems that maybe the way to make end-users' lives a little easier is to publish a v2.0.1 with something like the following in the `go.mod` file:

```
retract (
    v2.0.0 // Published accidentally.
    v2.0.1 // Contains retractions only.
)
```

**Comment by nelz9999** [comment]
May solve some of this issues as mentioned on #440 ?

**Comment by stevenh** [comment]
Interesting, as v2.0.0 was never published it's still flagged as incompatible so shouldn't be considered.

If we did a v2.0.1 I would be concerned it would make the problem worse.

Is this something you have experience with @nelz9999 ?

**Comment by nelz9999** [comment]
Sorry to say that I don't have direct experience with this. 😢 

But I know that this project fields requests in this realm fairly frequently, so I thought I'd mention the new directive in case it might help.

**Comment by stevenh** [comment]
Thanks I’ll ask on go nuts to see if this would solve the issue

**Comment by stevenh** [comment]
@nelz9999 what do you recon to merging https://github.com/gomodule/redigo/pull/590 and tagging it v1.8.7?

It's not 100% clear if that will work, might need a v2.0.1, but I don't think it will do any harm?

**Comment by nelz9999** [comment]
@stevenh It might be worth a shot... It seems like it could be a low-risk experiment. 

But my reading of the documentation has me thinking that you have to roll forward to retract behind you.

**Comment by nelz9999** [comment]
> The new version must be higher than other release or pre-release versions; that is, the @latest version query should resolve to the new version before retractions are considered.

**Comment by stevenh** [comment]
So sounds like I need to tag v2.0.1 which can be incompatible.
