### ISSUE TITLE
How to deal with errors that occur when connecting to the redis pool ？

### ISSUE THREAD

**Issue by daniuEvan** [gomodule/redigo#586]
How to deal with errors that occur when connecting to the redis pool ？

**Comment by daniuEvan** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/49090129/146486777-784f139c-07cd-4847-b0a0-22904aaa6a0b.png">

waht can I do  when connecting to the redis pool happend errors ？

**Comment by zuoshuwen** [comment]
```
c, err := redis.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		return nil, err
	}
	return c, nil
```
