### ISSUE TITLE
go 1.17+ depth require v2.0.0 in submodule 

### ISSUE THREAD

**Issue by RelicOfTesla** [gomodule/redigo#593]
```
// thrid module, can not edit code
base.project     
   import  "github.com/gomodule/redigo/redis"

#cat base.project/go.mod 
go 1.14
require  github.com/gomodule/redigo v2.0.0+incompatible
```
```
test.project
   import "base.project"

#cat test.project/go.mod
go 1.17
require github.com/gomodule/redigo v1.8.8+incompatible // indirect

```

```bash
cd test.project
go mod tidy
cat go.mod
....
go 1.17
require  github.com/gomodule/redigo v2.0.0+incompatible // indirect
....
```
**Is auto change to invalid version!!**

Maby change old tag v2.0.0 to bakV2.0.0 ??
Or change v.1.8.8 => v3 ?

**Comment by stevenh** [comment]
v2.0.0+incompatible was revoked by v1.8.8 as its not maintained and should not be used.

Any third party modules using redigo should be v1.x series.

**Comment by ping-localhost** [comment]
I'm having a slightly different issue than @RelicOfTesla. No matter what I do, Golang 1.17.5 always updates to `v2.0.0+incompatible`. 

When using `@latest` v2.0.0 will always be used, because of semver. Please resolve this by removing/renaming the tag or tagging v1.8.8 as v3.

**Comment by stevenh** [comment]
@latest **shouldn't** use v2.0.0 as its been retracted. We can't remove the v2.0.0 as that would break those that do want it.

Could you check what the following reports:
```shell
go version go1.17 linux/amd64
go list -m -versions github.com/gomodule/redigo
```

**Comment by stevenh** [comment]
Just tested here in a new pkg to see what happened and it did pickup 1.8.8
```shell
$ go mod init test.com/wibble
go: creating new go.mod: module test.com/wibble
go: to add module requirements and sums:
       go mod tidy
$ go mod tidy
go: finding module for package github.com/gomodule/redigo/redis
go: found github.com/gomodule/redigo/redis in github.com/gomodule/redigo v1.8.8
$ more go.mod
module test.com/wibble

go 1.17

require github.com/gomodule/redigo v1.8.8
```

**Comment by ping-localhost** [comment]
Confirmed. Not sure what's happening in my other project then, but I guess it's an unrelated issue. My apologies for wasting your time.

**Comment by stevenh** [comment]
No problem glad you're all sorted @ping-localhost 👍

**Comment by stevenh** [comment]
So to be clear, third party modules need to be go v1.16 and above (required for retract support), and then when updated they will pickup v1.8.8 or above.
