### ISSUE TITLE
outdated information on pkg.dev.go

### ISSUE THREAD

**Issue by pabigot** [gomodule/redigo#602]
While the current version of this package can be found on [pkg.go.dev](https://pkg.go.dev/github.com/gomodule/redigo), if you go to the [subdirectory link](https://pkg.go.dev/github.com/gomodule/redigo@v1.8.8/redis) where all the documentation is, the upper left corner shows the version and a red background link "Go to latest".

That link takes one to [this](https://pkg.go.dev/github.com/gomodule/redigo/redis) which is v1.7.1, and is very much out of date.  (In fact, that the one I found first, and it was only while researching for this issue that I stumbled upon the current one.)

I don't know if anything can be done about this.  Possibly a support request per https://pkg.go.dev/about#removing-a-package from a maintainer of this project would help: it may be that removing the separate nested version of the package from the repository would eliminate the bad link; or it may be a "feature" of multiple packages in a single repository.  Though [influxdb](https://pkg.go.dev/github.com/influxdata/influxdb-client-go/v2) has a similar multi-package layout without these problems.

**Comment by stevenh** [comment]
Thanks for flagging @pabigot that does look like a bug in pkg.go.dev.

**Comment by stevenh** [comment]
Fixed by https://github.com/gomodule/redigo/pull/604
