### ISSUE TITLE
Redigo client connection does NOT reused/returned to the Pool post close() call. 

### ISSUE THREAD

**Issue by JayShahSTL** [gomodule/redigo#610]
Ask questions at https://stackoverflow.com/questions/ask?tags=go+redis

We have specific use case where we are using redis-graph which uses **redigo** connections underlying. We are using redigo **Pools** for achieving concurrency. However, seems for every Close() call for the redigo connection, connections are NOT getting returned back to the Pool. 

As, per documentation of redigo API reference, the application shall close() the redigo connection, once usage is done. This behavior seems to re-create the new underlying network level connection with redis server in the even though from the Pool(). 

Redigo Pool implementation does NOT provide a way to return the **used redigo connections back to Pool,** so that next time those can be reused.

**Comment by stevenh** [comment]
Calling `conn.Close()` is the way to return a connection to the pool.

Do you have a test case which demonstrates this behaviour?

**Comment by stevenh** [comment]
As there's no information on this I'm going to close, if it's still and issue feel free to reopen
