### ISSUE TITLE
Just noticed a suspicious change in Redigo wiki

### ISSUE THREAD

**Issue by FZambia** [gomodule/redigo#631]
Closing, reported to Github and will reach repo maintainer over email.

**Comment by stevenh** [comment]
Thanks for flagging @FZambia I've edited the page and removed.

**Comment by stevenh** [comment]
I've also locked Wiki at least for now.

**Comment by FZambia** [comment]
Thanks, could not find your email @stevenh, maybe you can reach me out over email in my profile?
