### ISSUE TITLE
Need a way to execute arbitrary redis commands on a connection from a `Pool`

### ISSUE THREAD

**Issue by dcormier** [gomodule/redigo#635]
The `Pool` interface changed in v3. In [v2 and prior, `Pool.Get()`](https://pkg.go.dev/github.com/go-redsync/redsync#Pool) returned [a `github.com/gomodule/redigo/redis.Conn`](https://pkg.go.dev/github.com/gomodule/redigo/redis#Conn), which you can call `.Do()` on to execute arbitrary redis commands ([there are many](https://redis.io/commands/)).

The [`Pool` interface from v3 on](https://pkg.go.dev/github.com/go-redsync/redsync/v3/redis#Pool) returns a [github.com/go-redsync/redsync/v4/redis.Conn](https://pkg.go.dev/github.com/go-redsync/redsync/v4/redis#Conn), which only exposes helper methods and _not_ a method for executing arbitrary redis commands (other than through scripting).

I have a need to redis commands other than those for which [github.com/go-redsync/redsync/v4/redis.Conn](https://pkg.go.dev/github.com/go-redsync/redsync/v4/redis#Conn) does not expose methods. Scripting is unnecessarily complex to issue single commands.

It would be useful if the `Conn` interface exposed something like [the `github.com/gomodule/redigo/redis.Conn.Do()` method](https://pkg.go.dev/github.com/gomodule/redigo/redis#Conn) for arbitrary redis commands. It would be simple, but it would require a incrementing the major version since it breaks compatibility. As [bcmills pointed out](https://github.com/gomodule/redigo/issues/634#issuecomment-1297182499) in #634, that's why [returning an interface is not a good idea](https://github.com/golang/go/wiki/CodeReviewComments#interfaces).

**Comment by stevenh** [comment]
I think you posted this in the wrong repo, looks like you're trying to report something to [github.com/go-redsync/redsync/issues](https://pkg.go.dev/github.com/go-redsync/redsync/issues)

**Comment by dcormier** [comment]
Yes, you're right. Sorry about that. I've created go-redsync/redsync#104.
