### ISSUE TITLE
Act subscribe immediately without receive message

### ISSUE THREAD

**Issue by timandy** [gomodule/redigo#636]
Hi , Is there a method to act subscribe immediately and receive non message?
The current version of `Subscribe()` does not support waiting for a response from Redis.

Like:
```go
sub := client.Subscribe(queryResp)
sub.Active()  // TODO 
ch := sub.Channel()
go func() {
    for msg := range ch {
	     //do with msg
    }
} 
```

**Comment by stevenh** [comment]
Subscriptions are [covered in the docs here](https://pkg.go.dev/github.com/gomodule/redigo/redis#hdr-Publish_and_Subscribe) github issues are for bugs or feature request, not usage discussions.
