### ISSUE TITLE
Could you remove v2.0.0 tag

### ISSUE THREAD

**Issue by studyzy** [gomodule/redigo#639]
This is an invalid tag name, could you delete it?

**Comment by stevenh** [comment]
I can’t do that as people may be using it. However as the version has been [retracted](https://github.com/gomodule/redigo/blob/master/go.mod#L7) it’s not available via go mod so shouldn’t be having any impact to the ecosystem

**Comment by studyzy** [comment]
OK, historical accident😭

**Comment by RelicOfTesla** [comment]
@stevenh  Perhaps you can consider using an additional v3.0 tag to override v2.0. Some versions of Go have been forced to update to v2.

**Comment by stevenh** [comment]
As 2.0 is redacted no versions should be forced to update as it's essentially not valid for any new consumers. Anyone who has it is explicitly specified should be able to downgrade
