### ISSUE TITLE
Not able to connect when Redis Password contains"/"

### ISSUE THREAD

**Issue by 0xj0el** [gomodule/redigo#645]
DialUrl seems to be failing when password contians "/" in it. Is there an encoding issue that it doesnt encode forward slash. Found this issue while installing harbor with redis credentials passed in harbor.yml file.

**Comment by 0xj0el** [comment]
currently I am manually encoding the "/" in the password with "%2F" and passing it harbor.yml and seems to be working.

**Comment by stevenh** [comment]
The URL passed to `DialURL` does need to be correctly formatted so ensuring your `password` and `userame` are URL encoded is correct.
