### ISSUE TITLE
Wait pool timeout?

### ISSUE THREAD

**Issue by nicklaros** [gomodule/redigo#646]
When `Wait` configuration on pool is set to `true`, is there any timeout for getting a connection from pool? or will it block until the app succesfully get available connection?

**Comment by mna** [comment]
By default it would block indefinitely if you use `Pool.Get()`, but you can use `Pool.GetContext` and provide a context with a timeout so that it fails if it waits for longer than the timeout: https://pkg.go.dev/github.com/gomodule/redigo/redis#Pool.GetContext

**Comment by stevenh** [comment]
@mna is correct, `Pool.Get()`  will block until a connection is available.

To clarify the use of issues is for bugs in the code, not for general usage support please use tools like [stackoverflow](https://stackoverflow.com/) for that.
