### ISSUE TITLE
Close TLS connection if handshake timeout

### ISSUE THREAD

**Issue by Oleglacto** [gomodule/redigo#671]
If TLS enabled and we got tlsHandshakeTimeoutError, we will not close TLS connection [here](https://github.com/gomodule/redigo/blob/247f6c0e0a0ea200f727a5280d0d55f6bce6d2e7/redis/conn.go#L271)

I suggest next improvements:
```go
                innerCtx, cancel := context.WithCancel(ctx) // new
		if d := do.tlsHandshakeTimeout; d != 0 {
			timer := time.AfterFunc(d, func() {
				cancel()
				errc <- tlsHandshakeTimeoutError{}
			})
			defer timer.Stop()
		}
		
		go func() {
			errc <- tlsConn.HandshakeContext(innerCtx) // new
		}()
```

If we got timeout, TLS package close connection by cancel ctx [here](https://cs.opensource.google/go/go/+/master:src/crypto/tls/conn.go;l=1547).

I think it's easiest solution of connection leak

**Comment by stevenh** [comment]
Looks reasonable @Oleglacto happy to take a PR.

**Comment by Oleglacto** [comment]
How to make pr? I can't push into rep

**Comment by stevenh** [comment]
You create a fork, push to your fork on a new branch e.g. `fix/tls-close` then raise a PR from that.

**Comment by Oleglacto** [comment]
Sorry, i made deep research for this issue, and it's works fine.
