### ISSUE TITLE
How to add subscriptions while receiving messages?

### ISSUE THREAD

**Issue by aktau** [gomodule/redigo#71]
In my project I have a goroutine running that basically waits for messages from a few redis pubsub channels:

``` go
for {
  switch v := r.Receive().(type) {
    // ...
  }
}
```

I also have another goroutine that's waiting on a go channel, and whenever it gets a value on that channel, it subscribes to that value. Like this:

``` go
select {
case newRedisChan := <-subscribe:
  r.Subscribe(newRedisChan) // this is the same r as in the last example, but we're in a different go routine
}
```

Needless to say, this provoked a data race (all hail the race detector) to show me the error of my ways. For reference:

``` bash
WARNING: DATA RACE
Read by goroutine 27:
  github.com/garyburd/redigo/redis.(*pooledConnection).get()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pool.go:262 +0x4c
  github.com/garyburd/redigo/redis.(*pooledConnection).Send()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pool.go:338 +0x5a
  github.com/garyburd/redigo/redis.PubSubConn.Subscribe()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pubsub.go:69 +0x9c
  bitbucket.org/aktau/ansible-go/cache.func·002()
      /home/vagrant/go/src/bitbucket.org/aktau/ansible-go/cache/redis.go:212 +0x385

Previous write by goroutine 23:
  github.com/garyburd/redigo/redis.(*pooledConnection).get()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pool.go:263 +0xdc
  github.com/garyburd/redigo/redis.(*pooledConnection).Receive()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pool.go:354 +0x61
  github.com/garyburd/redigo/redis.PubSubConn.Receive()
      /home/vagrant/go/src/github.com/garyburd/redigo/redis/pubsub.go:97 +0x76
  bitbucket.org/aktau/ansible-go/cache.(*RedisCache).autoInvalidate()
      /home/vagrant/go/src/bitbucket.org/aktau/ansible-go/cache/redis.go:228 +0x4cb
```

So, I'd like to ask what the idiomatic way to do this is? If Receive() returned a channel I guess I wouldn't even need to create 2 goroutines, as I could just put it all in a select statement. So I guess there's a good reason Receive() is a straight method call.

Also, is it safe to Close the connection from another goroutine? Because that's what I've been doing (I don't see how else I should do it).

**EDIT**: after looking at https://github.com/garyburd/redigo/blob/d39ee8868a981f93ca8cb17cfb1faf12efff49a6/redis/pubsub_test.go#L51-L89 (I admit, I should've done that first), I can see that you more or less follow the same style. I wonder why that doesn't race for you...

**Comment by garyburd** [comment]
This issue was fixed by 7eff00e9b3cd9c85526bf0dd83feaa1a02da2762
