### ISSUE TITLE
Within reply.go,shouldn't return error:"redigo: nil returned"  when nothing got returned from Do(...)

### ISSUE THREAD

**Issue by AlexLuya** [gomodule/redigo#87]
There two reasons:
   1,break the api contract of redis:" If the key does not exist the special value nil is returned",not error
   2,confuse some conceptions,in my option,error means operation doesn't get completed due to some abnormal reasons.if user trying to get an nonexisted value,and operation get completed normally,then feed result to redis.String()/redis.Bool()...,this method should return results that obey the redis's api contract,like:(false,nil)/("",nil),not (false,error(redigo: nil returned))/("",error(redigo: nil returned)).

**Comment by paulja** [comment]
I'm glad I found the above comment (https://github.com/garyburd/redigo/issues/87#issuecomment-60807781), as I was scratching my head as to why this API would return errors when the key was missing (which is a common use-case for a cache). Would be great if the code sample above was also in the `String` code example... would have saved me some time 😄

**Comment by rfyiamcool** [comment]
+1
